### ISSUE TITLE
Failsafe does not work anymore in last deveopment build (may be limited to Spektrum sat only)

### ISSUE THREAD

**Issue by MJ666** [cleanflight/cleanflight#609] opened 2015-03-11 14:00 UTC
If you are using the last development version of Cleanflight please be sure to test failsafe carefuly. Our tests during last days showed some issues here and the NanoCopters don't behave as expected anymore. We usualy configure them to cut the motors after 0.2s when the rx signal failed (Lemon RX satellite is very sensitive to power drops) but this is not happening anymore. Here are the settings:

set failsafe_delay = 2
set failsafe_off_delay = 0
set failsafe_throttle = 1000

Usualy it cuts the motor and disarmed permanently and the LED which indicate the armed copter will flash only. You need to repower the FC to get it to fly again.

Better to be save than sorry. An version build on March 1st is still working fine. Unfortunately I don't keep all intermediate versions and was not able to track the problem down yet. May be it is related to this change:

https://github.com/cleanflight/clean...a5f0d031c63ee1

Looks to be there are a few more changes which could affect failsafe after this.

UPDATE: We now have finished testing. Failsafe is definitely broken in the last development build. This will be at least for using Spektrum compatible satellite receivers. With the setting above we would expect if we set something on the copter (running motors) and switch off the TX to see the following:

1. continue with the same operation for 0.2s
2. after this switch the motors off
3. disarm and disable arming

This is not happening anymore and the copter continuous with the same commands as long the TX is off. After switching the TX on again you can control the copter again.

Here is the test cycle we have used:

1.) applied part throttle
2.) turned off tx
3.) waited 15 seconds (copter kept running)
4.) turned tx back on, and had control 

All details also published in the following RCG thread:

http://www.rcgroups.com/forums/showpost.php?p=31023971&postcount=4474

This is a serious problem and likely will cause a flyaway. I hope not many users will fly with the development build yet.

**Comment by hydra** [comment] 2015-03-11 17:17
Yeah, looks like some investigation is required.  I'll look into it.  Thanks for the test report, much appreciated.

**Comment by hydra** [comment] 2015-03-11 17:18
Likely the spectrum RX driver needs updating a little for when the RX reports a failsafe condition.

**Comment by MJ666** [comment] 2015-03-11 17:30
Here I wrote something we have seen from experience with the Lemon RX DSM2 and DSMX satellite receivers:

http://www.rcgroups.com/forums/showpost.php?p=31027412&postcount=4496

**Comment by hydra** [comment] 2015-03-14 22:29
Did a bit of work on this in 7d6e4aa3900370c8a11a020337ea2079846f3de6.

Please re-test with Spektrum RX and report back.

**Comment by hydra** [comment] 2015-03-14 23:03
More changes done in e08c83fdc9142fd2efdf0098710fc48bf194a464

Please re-test a build that has both of those commits.

**Comment by MJ666** [comment] 2015-03-15 06:43
Will do as soon I will be back from traveling. Thanks.

**Comment by stronnag** [comment] 2015-03-15 16:03
hydra, latest build (2015-03-15) did not fix the issue for spektrum sat.

**Comment by hydra** [comment] 2015-03-15 19:58
ok, this will have to wait till i get back from austria so i can use my test equipment to debug it since the problem is not obvious to me.

**Comment by hydra** [comment] 2015-03-15 21:09
did a code walk in irc, found the problem, fixed by 1e7fb08b9d8afc98945b0eb77b6b55ce55c43888

**Closed by hydra** 2015-03-15 21:09 UTC
Labels: in-progress

**Comment by stronnag** [comment] 2015-03-15 21:12
Tested on Spektrum. Failsafe works again.

**Comment by hydra** [comment] 2015-03-15 21:17
@MJ666 @stronnag thanks for reporting and testing.

Just pasted this in the rcgroups thread:

The problem came about due to users wanting this:

https://github.com/cleanflight/clean...mment-75368567

Due to this bug several things happened:

1) all serial rx handlers use the same pattern
2) minor performance optimizations were made
3) sumd rx failsafe was improved (matches sbus failsafe behaviour)
4) spektrum rx code was cleaned up, magic numbers removed.
5) memory usage was slightly decreased.

All in all a pretty good result! This is yet another example of how open source communities help make everything better.
