### ISSUE TITLE
Hott telemetry problem (GR-24, Mx-20) on SP F4 Evo

### ISSUE THREAD

**Issue by manjoel** [cleanflight/cleanflight#2745] opened 2017-04-20 12:40 UTC
Hallo, i have an seriously pro f4 evo board, an GR-24 Hott receiver and an Mx-20 transmitter. On der Fctrl I have 2.0.1
Im connected over UART 2 for the receiver an the 4th pin is UART 5 by soldering the Pad TLM. In the configuration UART 2 = Serial RX and UART 5 = Telemetry output HOTT. I configuration tab telemetry is activated. I tested with Softserial and witout, but no telemetry.

I updated Mx-20 and Gr-24 firmware yesterday.

What could be the problem.

**Comment by hydra** [comment] 2017-04-20 21:43
No need for soft serial.

Double check the status of telemetry inversion setting, that's probably the issue, the default is ON but HoTT isn't inverted.  Try this in the CLI.

```
set tlm_inversion=OFF
save
```

Please report back ASAP.  

Certainly I have not updated the firmware on either the MX20 or GR24 for a LONG time so maybe the HoTT code is out of date but I don't think so.

**Comment by manjoel** [comment] 2017-04-21 04:56
I switched off and on again telemetry and added "set tlm_inversion=OFF" I will reset the MX-20 to bee sure not having an error here

My dump

# resources
resource BEEPER 1 C15
resource MOTOR 1 C06
resource MOTOR 2 C07
resource MOTOR 3 C09
resource MOTOR 4 C08
resource MOTOR 5 B06
resource MOTOR 6 B07
resource MOTOR 7 B01
resource MOTOR 8 B00
resource MOTOR 9 B10
resource MOTOR 10 B11
resource MOTOR 11 NONE
resource MOTOR 12 NONE
resource SERVO 1 A09
resource SERVO 2 A10
resource SERVO 3 NONE
resource SERVO 4 NONE
resource SERVO 5 NONE
resource SERVO 6 NONE
resource SERVO 7 NONE
resource SERVO 8 NONE
resource PPM 1 A03
resource PWM 1 A03
resource PWM 2 A02
resource PWM 3 A09
resource PWM 4 A10
resource PWM 5 NONE
resource PWM 6 NONE
resource PWM 7 NONE
resource PWM 8 NONE
resource LED_STRIP 1 A01
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 3 B10
resource SERIAL_TX 4 C10
resource SERIAL_TX 5 C12
resource SERIAL_TX 6 NONE
resource SERIAL_TX 7 NONE
resource SERIAL_TX 8 NONE
resource SERIAL_TX 9 NONE
resource SERIAL_TX 10 NONE
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 3 B11
resource SERIAL_RX 4 C11
resource SERIAL_RX 5 D02
resource SERIAL_RX 6 NONE
resource SERIAL_RX 7 NONE
resource SERIAL_RX 8 NONE
resource SERIAL_RX 9 NONE
resource SERIAL_RX 10 NONE

# mixer
mixer QUADX

mmix reset


# servo
servo 0 1000 2000 1500 100 -1
servo 1 1000 2000 1500 100 -1
servo 2 1000 2000 1500 100 -1
servo 3 1000 2000 1500 100 -1
servo 4 1000 2000 1500 100 -1
servo 5 1000 2000 1500 100 -1
servo 6 1000 2000 1500 100 -1
servo 7 1000 2000 1500 100 -1

# servo mix
smix reset



# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -OSD
feature -UNUSED
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SDCARD
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -ESC_SENSOR
feature -ANTI_GRAVITY
feature RX_SERIAL
feature FAILSAFE
feature TELEMETRY
feature RSSI_ADC
feature OSD

# beeper
beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper BLACKBOX_ERASE

# map
map TAER1234

# serial
serial 20 1 115200 57600 0 115200
serial 0 0 115200 57600 0 115200
serial 1 64 115200 57600 0 115200
serial 2 0 115200 57600 0 115200
serial 3 0 115200 57600 0 115200
serial 4 8 115200 57600 0 115200

# led
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0
mode_color 7 0 3

# aux
aux 0 0 0 900 900
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
adjrange 12 0 0 900 900 0 0
adjrange 13 0 0 900 900 0 0
adjrange 14 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# vtx
vtx 0 0 0 0 900 900
vtx 1 0 0 0 900 900
vtx 2 0 0 0 900 900
vtx 3 0 0 0 900 900
vtx 4 0 0 0 900 900
vtx 5 0 0 0 900 900
vtx 6 0 0 0 900 900
vtx 7 0 0 0 900 900
vtx 8 0 0 0 900 900
vtx 9 0 0 0 900 900

# rxfail
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# master
set align_gyro = DEFAULT
set gyro_lpf = OFF
set gyro_sync_denom = 1
set gyro_lowpass_type = PT1
set gyro_lowpass = 90
set gyro_notch1_hz = 400
set gyro_notch1_cutoff = 300
set gyro_notch2_hz = 200
set gyro_notch2_cutoff = 100
set moron_threshold = 48
set gyro_use_32khz = ON
set gyro_isr_update = OFF
set align_acc = DEFAULT
set acc_hardware = AUTO
set acc_lpf_hz = 10
set acc_trim_pitch = 0
set acc_trim_roll = 0
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set baro_hardware = AUTO
set baro_tab_size = 21
set baro_noise_lpf = 600
set baro_cf_vel = 985
set baro_cf_alt = 965
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_interp = AUTO
set rc_interp_ch = RP
set rc_interp_int = 19
set fpv_mix_degrees = 0
set max_aux_channels = 14
set serialrx_provider = SUMD
set sbus_inversion = ON
set spektrum_sat_bind = 0
set spektrum_sat_bind_autoreset = 1
set airmode_start_throttle = 1350
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_halfduplex = OFF
set input_filtering_mode = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SDCARD
set blackbox_on_motor_test = OFF
set min_throttle = 1070
set max_throttle = 2000
set min_command = 1000
set digital_idle_value = 450
set use_unsynced_pwm = OFF
set motor_pwm_protocol = ONESHOT125
set motor_pwm_rate = 480
set motor_pwm_inversion = OFF
set thr_corr_value = 0
set thr_corr_angle = 800
set failsafe_delay = 10
set failsafe_off_delay = 10
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gimbal_mode = NORMAL
set bat_capacity = 0
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set vbat_hysteresis = 1
set current_meter = ADC
set battery_meter = ADC
set bat_detect_thresh = 55
set use_vbat_alerts = ON
set use_cbat_alerts = OFF
set cbat_alert_percent = 10
set vbat_scale = 110
set ibata_scale = 400
set ibata_offset = 0
set ibatv_scale = 0
set ibatv_offset = 0
set beeper_inversion = ON
set beeper_od = OFF
set beeper_frequency = 0
set yaw_motors_reversed = OFF
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lowpass_hz = 0
set tri_unarmed_servo = ON
set channel_forwarding_start = 4
set reboot_character = 82
set serial_update_rate_hz = 100
set accxy_deadband = 40
set accz_deadband = 40
set acc_unarmedcal = ON
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set small_angle = 25
set auto_disarm_delay = 5
set disarm_kill_switch = ON
set gyro_cal_on_first_arm = OFF
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = ON
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set fixedwing_althold_reversed = OFF
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set yaw_control_reversed = OFF
set pid_process_denom = 4
set tlm_switch = OFF
set tlm_inversion = OFF
set sport_halfduplex = OFF
set frsky_default_lat = 0
set frsky_default_long = 0
set frsky_gps_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_int = 5
set pid_in_tlm = OFF
set ibus_report_cell_voltage = OFF
set ledstrip_visual_beeper = OFF
set sdcard_dma = ON
set osd_units = METRIC
set osd_rssi_alarm = 20
set osd_cap_alarm = 2200
set osd_time_alarm = 10
set osd_alt_alarm = 100
set osd_vbat_pos = 2092
set osd_rssi_pos = 2088
set osd_flytimer_pos = 2081
set osd_ontimer_pos = 2102
set osd_flymode_pos = 2413
set osd_throttle_pos = 2273
set osd_vtx_channel_pos = 2425
set osd_crosshairs = 2248
set osd_horizon_pos = 2248
set osd_current_pos = 2433
set osd_mah_drawn_pos = 2401
set osd_craft_name_pos = 2442
set osd_gps_speed_pos = 218
set osd_gps_lon = 2546
set osd_gps_lat = 2514
set osd_gps_sats_pos = 51
set osd_altitude_pos = 2295
set osd_pid_roll_pos = 2471
set osd_pid_pitch_pos = 2503
set osd_pid_yaw_pos = 2535
set osd_power_pos = 2369
set osd_pidrate_profile_pos = 2393
set osd_battery_warning_pos = 2185
set osd_avg_cell_voltage_pos = 2124
set task_statistics = ON
set debug_mode = NONE
set vtx_band = 4
set vtx_channel = 1
set vtx_power = 0
set displayport_msp_col_adjust = 0
set displayport_msp_row_adjust = 0

# profile
profile 0

set d_lowpass_type = BIQUAD
set d_lowpass = 100
set d_notch_hz = 260
set d_notch_cut = 160
set vbat_pid_gain = OFF
set pid_at_min_throttle = ON
set anti_gravity_thresh = 350
set anti_gravity_gain = 1000
set setpoint_relax_ratio = 100
set d_setpoint_weight = 60
set yaw_accel_limit = 100
set accel_limit = 0
set iterm_windup = 50
set yaw_lowpass = 0
set pidsum_limit = 500
set pidsum_limit_yaw = 400
set p_pitch = 58
set i_pitch = 50
set d_pitch = 35
set p_roll = 44
set i_roll = 40
set d_roll = 30
set p_yaw = 70
set i_yaw = 45
set d_yaw = 20
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 50
set i_level = 50
set d_level = 100
set p_vel = 55
set i_vel = 55
set d_vel = 75
set level_sensitivity = 55
set level_limit = 55
set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83

# rateprofile
rateprofile 0

set rc_rate = 100
set rc_rate_yaw = 100
set rc_expo = 0
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_srate = 70
set pitch_srate = 70
set yaw_srate = 70
set tpa_rate = 10
set tpa_breakpoint = 1650

**Comment by hydra** [comment] 2017-04-22 01:28
ok, thanks for the details, I will did mine out this weekend and give it a test to make sure it still works.   Please also try powering everything off and then on, with the HoTT firmware i was using the HoTT receivers only scan for telemetry for a short while after startup.

**Comment by hydra** [comment] 2017-04-22 11:46
problem confirmed, the issue is that the TX pin is not allocated due to the initial serial port mode.  This is a change from betaflight that broke it.  I will look at fixing it now.

**Comment by hydra** [comment] 2017-04-22 12:23
See also https://github.com/cleanflight/cleanflight/issues/2754

**Comment by hydra** [comment] 2017-04-22 13:27
actually, it turns out there are a number of issues:

1) TX pin not allocated correctly.
2) missing support for hardware bidirectional uarts
3) incorrect documentation in the spracingf4evo manual.
4) the only supported hardware uart ports are UART1/2/3.

to fix your issue, do not use UART5 on the SPRacingF4EVO and use uart1,2 or 3, connect both TX and TX pins and a diode as per the manual.  UART4 cannot be used in < CF 2.0.1

Cleanflight v2.0.2 adds:
* experimental support for HoTT on bidirection uninverted serial ports that support bi-directional transfers (i.e. using one wire, without a diode) - but not an always-inverted uart as found on the SPRacingF4EVO UART5.
* two-wire + diode all hardware uart ports (in addition to softserial/uart1/2/3)

The HoTT telemetry code needs updating, i created a seperate issue #2754 to track this.

**Comment by hydra** [comment] 2017-04-22 15:25
SPRacingF4EVO manual has been updated.

**Comment by hydra** [comment] 2017-04-22 15:25
Cleanflight v2.0.2 is out now - https://github.com/cleanflight/cleanflight/releases/tag/CLFL_v2.0.2

**Comment by hydra** [comment] 2017-04-22 20:17
I'll close this now, nothing more to do.  If it still doesn't work for you after reading the latest manual and using the latest cleanflight please create a new issue and reference this one.

**Comment by hydra** [comment] 2017-04-22 20:18
I should add, once you've tested it and got it working please leave a message here.

**Closed by hydra** 2017-04-22 20:17 UTC
Labels: requires-feedback, support

**Comment by manjoel** [comment] 2017-04-23 07:25
I tryed little bit arround Uart 1 is used for pdb/osd.
So I tryed 3+4, but nothing worked. I resetted the board, I tryed with inversion.
Tomorrow I will look for an diode to verify, if there could be an other problem.
