### ISSUE TITLE
Chrome 41 configurator tab display problem

### ISSUE THREAD

**Issue by Vincent81** [cleanflight/cleanflight#420] opened 2015-01-24 11:56 UTC
Hello
no connection :
![clean1](https://cloud.githubusercontent.com/assets/962113/5887294/4d70d7ae-a3c8-11e4-9e39-6ebdfb58320f.png)
With connection  :
![clean2](https://cloud.githubusercontent.com/assets/962113/5887297/5f124e48-a3c8-11e4-8852-0571654dc92a.png)
but it works anyway.

**Comment by tracernz** [comment] 2015-01-24 21:50
Yes, I'm also getting this on OS X with the newest configurator.

**Comment by fiveangle** [comment] 2015-01-24 21:58
Works for me.  Is it intermittent or do they never show up ?

-=dave

**Comment by thenickdude** [comment] 2015-01-24 22:53
Works for me on OS X on 0.60.0 and 0.60.1 (Yosemite, Retina display). Does
resizing the window cause them to pop back into existence?

**Comment by tracernz** [comment] 2015-01-24 23:30
I'm running 0.6.0 on Chrome 41, Yosemite, retina screen. It does switch to  The tabs disappear when I connect and reappear when I disconnect they reappear. Resizing the window doesn't make them come back. Even though they're not visible I can still click them and switch pages. I haven't had this issue until yesterday but I'm not exactly sure which version it began to happen unfortunately.

**Comment by hydra** [comment] 2015-01-24 23:40
Chrome 41 is beta version i think.
```
Version 40.0.2214.91 (64-bit)
 Google Chrome is up to date.
```
Is what my OSX Yosemite box says.

**Comment by hydra** [comment] 2015-01-24 23:41
p.s.  this is raised in the wrong issu tracker. it should be raised here: https://github.com/cleanflight/cleanflight-configurator/issues

**Comment by tracernz** [comment] 2015-01-24 23:42
I've just confirmed this is a problem with Chrome 41 (beta). Updated my Windows machine from 40 (tabs worked fine) to 41 and it now it's also broken.

**Comment by thenickdude** [comment] 2015-01-25 00:20
I see that on Chrome 41. Looks like it's fixed by adding the style
"overflow:hidden" to the <ul> that contains the tabs. (Adding
overflow:hidden causes an element's height to grow to contain any floated
elements that are contained inside it).

**Comment by hydra** [comment] 2015-01-26 14:13
this fix has been merged in to latest configurator development branch.

**Closed by hydra** 2015-01-26 14:13 UTC
