### ISSUE TITLE
Cleanflight SPRacing F3 falls out of the sky 

### ISSUE THREAD

**Issue by NicolasLaureyns** [cleanflight/cleanflight#1641] opened 2015-12-30 17:36 UTC
Hello, 

I'm having a problem with my quad, on irregular base it just flips and falls out of the sky.. 
Sometimes when 5 min flying, sometimes 10 sec.. 

Turned on blackbox and here's an image  when it flips and falls: 
Could someone explain me what's happening ? 
![image](https://cloud.githubusercontent.com/assets/16491852/12054245/068475f6-af22-11e5-8aa5-dce9de6e9a40.png)

Another one: 
![image](https://cloud.githubusercontent.com/assets/16491852/12054938/40b561ee-af28-11e5-908e-cb66b0fa51f6.png)

You can find the whole blackbox logfile in attachment. 
[blackbox_log_2015-12-30_174732.TXT](https://github.com/cleanflight/cleanflight/files/75016/blackbox_log_2015-12-30_174732.TXT)
it's run 2 and 7. 

Small video when it flips: 
https://youtu.be/fyLdCBZ5yu4

Setup: 
Blackout 360 frame 
Cobra 2208 200Kv motors
SPRacing F3 FC (Running latest firmware 1.11.0) 
Kiss ESC 30A 
HQProp 6x4.5 Bullnose 
FrSky X8R receiver 
Turingy 3200Mah A-spec battery 

At first I thought it were the ESC's so I set the looptime from 2000 to 2500 to test, but still the same problem. 
Seems to me that the FC just stops at the end  on run 7? 

Thanks in advance.

**Comment by joshuabardwell** [comment] 2015-12-30 18:14
The log ends before the board disarms, which is why the traces end with square dots. This is a normal occurrence under flight conditions where there is too much data for the UART or the SD card to write at once. Most likely explanation is that the rapidly changing data that resulted from the copter flipping out overwhelmed the compression on the Blackbox link and overwhelmed the serial output. This isn't a bug.

Nothing in your Blackbox log seems to indicate a bug in Cleanflight. Most likely explanation IMO is a damaged gyro in the SP3 that is sporadically flipping out.

GitHub is for bug tracking, not support issues. If you agree that this is not a bug, please close this issue and get further support over on the RCGroups CleanFlight thread.

**Comment by ledvinap** [comment] 2015-12-30 18:39
@NicolasLaureyns : Where do you record blackbox data? Onboard chip or openlog?

**Comment by NicolasLaureyns** [comment] 2015-12-30 18:42
@ledvinap The onboard chip of the SP3. 
@joshuabardwell The board is brand new, the only crashes I made is because of the flipping..

**Comment by ledvinap** [comment] 2015-12-30 18:49
Maybe board resets? 
What state is the quad after crash?

How do you power the board?

**Comment by NicolasLaureyns** [comment] 2015-12-30 18:54
@ledvinap I reflashed the firmware on the board after some crashes, problem still presists. 
Gonna try to fly with the stock settings, tomorrow. 

The state of the board is disarmed, board is powered with Pololu 5V, 1A Step-Down Voltage Regulator D24V10F5

**Comment by varoudis** [comment] 2015-12-30 22:46
not sure if its related but I get reboot sequence with SPF3 when there is a lot a acc/gyro activity. Shaking the quad or slapping it a bit. All of this only when armed. If not armed (via switch) everything is ok.

There is a closed ticket on beta flight repo.

**Comment by hydra** [comment] 2016-01-08 17:58
It's probably a wiring issue or a defective board.  Which retailer did you buy the board from?  Have you contacted them?

**Closed** 2016-01-08 18:00 UTC
Labels: support
