### ISSUE TITLE
spektrum_sat_bind resets itself to 0 after binding

### ISSUE THREAD

**Issue by BlindingBright** [cleanflight/cleanflight#765] opened 2015-04-13 22:06 UTC
For some this may be a feature but it's keeping me from being able to rebind in the field to other craft. I'm probably the only dork that is affected by this.

**Comment by MJ666** [comment] 2015-04-14 15:38
This is intended behavior. If this is set permanently the RX will always go into bind mode. Some FC's have an hardware bind plug in this case the value will not be reset and bind will only activated if the bind plug is set.

**Comment by hydra** [comment] 2015-04-16 01:11
Closing as invalid.  Maybe a PR to update the documentation would help?

**Closed** 2015-04-16 01:11 UTC
