### ISSUE TITLE
CC3D without Mag detection (external HMC5883L @Flexi Port)

### ISSUE THREAD

**Issue by Ludn** [cleanflight/cleanflight#598] opened 2015-03-08 18:50 UTC
i did read #525 which should be included in v1.7.2?- not sure if my board GY271 is really ok.
Checked SDA SCL interchange already.

Set up Ports UART3 = unused, set mag_hardware=2.
This is the only way to get after boot up the sequence as follows.
Scaned with a logic analyser, does not look too bad:

Write 0xEE + NAK
Write 0xEE+ NAK, Write 0x3C + ACK, 0x00 +ACK, Read 0x3D + ACK, 0x48 + NACK
followed by silence..
-Should it work in this configuration, may be the pull downs are too strong, any ideas?

**Comment by thenickdude** [comment] 2015-03-09 09:24
It's impossible to set `mag_hardware` = 2 in 1.7.2 using the CLI due to a bug which was fixed in this later commit:

https://github.com/cleanflight/cleanflight/commit/8a541a9fa28197da2d3f2b858ba837be5b9cea1d

Use "dump" to confirm the actual value of your `mag_hardware` setting.

**Comment by Ludn** [comment] 2015-03-09 18:55
Thanks, can't wait getting this brilliant project to work also on other flight controller like sparky or flip32+.

'set mag_hardware = 2' writing on CC3D is confirmed using 'get' or 'dump'.
Indeed other setting does also create I2C communication on flexi port 682ms after boot up as noted above. However 'Mag' is not detected also an additional GPS doesn't help on this.

I have seen some SW-fragments that interrupt connection to DRDY needed, is it?

Unfortunately i am more into HW and not familiar with SW-repository and compiling (yet). I am happy for hints/links to start with to get your commit compiled to a bin-file to test it.

Since i found the HMC5883L driver a was hopping for native compass support. -It' working on the Naze32 version, isn't it? Does a different port make life easier?

**Comment by Ludn** [comment] 2015-03-10 19:59
Did remove 2k2 pull-ups on compass board, still no success :(
Communication still stops after Write 0x3C + ACK, 0x00 +ACK, Read 0x3D + ACK, 0x48 + NACK

Isn't here anyone using a CC3D with a working compass who can give me hint?

**Comment by ledvinap** [comment] 2015-03-10 20:18
Can you post complete communication with HMC5883L ?

**Comment by Ludn** [comment] 2015-03-10 20:28
an overview first:
![image](https://cloud.githubusercontent.com/assets/11378494/6584537/571dfda0-c76c-11e4-904a-7a86c744fea9.png)

in detail:
![image](https://cloud.githubusercontent.com/assets/11378494/6584467/db0088aa-c76b-11e4-8be7-617597da2d53.png)
![image](https://cloud.githubusercontent.com/assets/11378494/6584482/06815f5e-c76c-11e4-9876-fc265991f91b.png)
![image](https://cloud.githubusercontent.com/assets/11378494/6584508/2e4c089a-c76c-11e4-907e-f9d74f9240d5.png)

**Comment by digitalentity** [comment] 2015-03-10 22:32
Communication looks really strange. It seems that magnetometer on your GY271 board is not responding to it's address. Can you post a photo of your GY271 board?

**Comment by digitalentity** [comment] 2015-03-10 22:37
This is how a proper initialization of HMC5883L compass look like on my CC3D + HMC5883L breakout board ![](https://cloud.githubusercontent.com/assets/11378494/6584508/2e4c089a-c76c-11e4-907e-f9d74f9240d5.png)

**Comment by ledvinap** [comment] 2015-03-10 22:47
0xee is BPM085 or MS5611, NAK is ok if no baro is installed.

Then register 0x0A (ID A) is read, 'H' (0x48) is returned correctly. 

That is last communication?

Where did you get 0x3C + ACK, 0x00 +ACK ?

**Comment by digitalentity** [comment] 2015-03-10 22:51
Oops, sorry, posted the wrong screenshot. This one was for BMP180 baro.

**Comment by Ludn** [comment] 2015-03-11 20:42
@ledvinap
yes, Read 0x3D,  0x48 is the last communication. Shouldn't it end with ACK?
0x3C, 0x00 was the same 3rd and last term. It might changed cause of the missing second unnecessary pull ups.
@digitalentity
could you send the right screenshot or confirm after Read 0x3D + ACK, 0x48 which happens  (NACK / ACK)

**Comment by ledvinap** [comment] 2015-03-11 21:46
@Ludn : Master send NAK on last byte to tell slave that transfer is done, so it should be OK. 

The code is here: https://github.com/cleanflight/cleanflight/blob/3e73b3de5304fd235586831fbcb391ac974ee942/src/main/drivers/compass_hmc5883l.c#L125

Maybe data are received incorrectly? Can you check with oscilloscope?

**Comment by digitalentity** [comment] 2015-03-11 22:53
@Ludn, NACK is ok, communication with my mag looks the same.
![screenshot](https://cloud.githubusercontent.com/assets/11059099/6608727/363a288c-c895-11e4-91e7-ba344ed2c327.png)

**Comment by hydra** [comment] 2015-03-13 08:10
Perhaps try running some other example code on your GY271 to first verify that the mag is actually working.

Once you've confirmed the mag on your board is working then please re-open this.

**Closed by hydra** 2015-03-13 08:10 UTC

**Comment by Ludn** [comment] 2015-03-21 16:42
Thank you to all, wanted to report that issue is fully solved with v1.8.0 cause communication is continued and MAG works well.
