### ISSUE TITLE
Parallel PWM Spektrum gear/ f-mode switch

### ISSUE THREAD

**Issue by stefan15** [cleanflight/cleanflight#754] opened 2015-04-11 11:00 UTC
I've installed Cleanflight v1.8.1 on my CC3D and connected the RX via the parallel interface. Unfortunately the gear or F-mode called switch stays on its center position (1500). The Bug #636 (which has been fixed?) is just as described as my problem so is this issue just appearing in my special case?

**Comment by hydra** [comment] 2015-04-14 15:25
Duplicate of #754

**Closed by hydra** 2015-04-14 15:25 UTC
