### ISSUE TITLE
disable failsafe and/or low voltage beep when connected via usb

### ISSUE THREAD

**Issue by iz3man** [cleanflight/cleanflight#646] opened 2015-03-19 09:39 UTC
if you just want to set some parameters or tune and connect the FC via usb it starts to beep. may be because of low voltage or failsafe as there is no transmitter turned on.
i think VBAT low voltage and FAILSAFE warnings in any case only make sense WITH a battery CONNECTED.

**Comment by thenickdude** [comment] 2015-03-19 10:04
Duplicate of #366

**Closed by thenickdude** 2015-03-19 10:04 UTC

**Comment by hydra** [comment] 2015-03-19 21:12
Thanks for closing this @thenickdude
