### ISSUE TITLE
Use Sonar on M5/M6 in RX_PPM Mode?

### ISSUE THREAD

**Issue by PowerSquirl** [cleanflight/cleanflight#747] opened 2015-04-09 10:11 UTC
Hi,

yesterday i got my NAZE32 Quad out of the basement after more than a year and had the idea to attach some HCSR04 to it. i used to modify the baseflight source files on my own for customizing which always had been a lot of hassle with setting up the toolchain etc... so i was pleased to read about the cleanflight fork actually constantly improving functionality and decided to switch to it. Thanks for all the work!

However i am using the FrSky D4R-II Rx and intend to stick with it. And if I'm clear, that prevents me from connecting the sonar to the Motor Pins 5 and 6. Is there any reason not to use that configuration or is it just not implemented (yet)?

ps

**Comment by hydra** [comment] 2015-05-06 20:41
Duplicate of #378

**Closed by hydra** 2015-05-06 20:41 UTC
