### ISSUE TITLE
No input signal from ch5 with pwm and vbat disabled

### ISSUE THREAD

**Issue by McJohn115** [cleanflight/cleanflight#1556] opened 2015-12-09 18:29 UTC
Hi Guys,
im using a CC3D with CF 1.10.0, a Spektrum AR610 RX and TAER settings, all channels works fine but i cant get a input on CH5 (AUX1 - 3 way switch for flightmodes). Vbat is disabled.
I thought it was fixed #612 but it seems not.

Any help for me?

**Comment by SteveAmor** [comment] 2015-12-09 18:33
Duplicate of #1542?  Is it ok if you configure as AETR?

**Comment by McJohn115** [comment] 2015-12-09 22:31
No, all channels interchanged but no signal on ch  5.

**Comment by McJohn115** [comment] 2015-12-10 09:40
Any other ideas?

**Comment by SteveAmor** [comment] 2015-12-10 14:03
Does V1.9.0 work as expected?

**Comment by McJohn115** [comment] 2015-12-10 14:40
No, i tried this 2 hours ago, same problem, and same with Betaflight.
With Openflight and Betaflight all channels works as they should.

**Comment by McJohn115** [comment] 2015-12-11 10:52
Are there any settings needed so i can see any movement on the AUX-Bar under the Reciever Tab in the CF Configurator?
I tried do set the Servoadjust on TX lower and higher but nothing happens.

**Comment by SteveAmor** [comment] 2016-01-08 20:35
@McJohn115   this is a support problem that should be worked through in the forums.  Please can you close this issue.

**Comment by dpfaffenbauer** [comment] 2016-01-09 15:21
is there any solution yet? i experience the same problem with a turnigy 9x8cv2 receiver.

**Comment by McJohn115** [comment] 2016-01-09 16:16
Sry i didnt find any solution, im using LibrePilot now, works excellent for me and 3D flying is possible.

**Comment by SteveAmor** [comment] 2016-01-09 19:17
Please close this issue.

**Closed** 2016-01-09 21:27 UTC
