### ISSUE TITLE
Autoland

### ISSUE THREAD

**Issue by CradyCopter** [cleanflight/cleanflight#212] opened 2014-12-13 03:47 UTC
An autoland feature similar to Arducopter's 'Land Mode' (also in latest rel. of Multiwii?) would be awesome -- especially for those people who have sonar installed.
I have an APM 2.6 on my larger multi and use the Land Mode whenever it gets too windy for me to set it down gracefully.

http://copter.ardupilot.com/wiki/land-mode/

**Comment by hydra** [comment] 2015-05-15 14:14
Duplicate of #234

**Closed by hydra** 2015-05-15 14:14 UTC
Labels: enhancement
