### ISSUE TITLE
Tricopter YAW servo changes not acknowledged in Configurator / FC

### ISSUE THREAD

**Issue by mrduncan626** [cleanflight/cleanflight#1167] opened 2015-07-27 14:20 UTC
I was using 1.8.1 on my tricopter which worked great.  Updating to 1.9.1, the configurator Servo settings (min, mid, max, and direction) are not being saved to the FC.  But, I do have control the servo via the radio in which servo seems to be set to some undetermined values.  I tried changing the direction of the servo in the CLI, but it also is not being saved to the FC.  I am currently using Configurator 0.65.0 and a Flip32 FC.

Switching back the 1.8.1, I can still configure the servo.

**Comment by SteveAmor** [comment] 2015-07-27 15:25
Duplicate of #991

**Closed** 2015-07-29 05:09 UTC
