### ISSUE TITLE
CC3D problem with the gyro on firmware 1.12.0

### ISSUE THREAD

**Issue by a6j** [cleanflight/cleanflight#1993] opened 2016-03-31 08:58 UTC
Board CC3D
Firmware 1.12.0
Frame tricopter 250
After updating the firmware to 1.12.0 I have detected a problem. After 3-5 seconds of flight copter starts to pull to the side.
Reset does nothing settings. Turning the controller also does not solve the problem. This issue was on firmware OP. With the transition to the CF this is not a problem only manifested itself on firmware 1.12.0. I downgrade 1.11.0 problem with deviation toward disappeared.
![cc3d](https://cloud.githubusercontent.com/assets/15672165/14170623/6b093658-f737-11e5-9c1b-856fef00be92.png)

**Comment by fftunes** [comment] 2016-04-01 18:47
Sounds like your cc3d suffers from vibration, which might become noticeable because of different default filter settings in the firmware?

**Comment by a6j** [comment] 2016-04-03 13:22
Yes vibration little is there, but not critical. How to solve this problem in the firmware 1.12.0?

**Comment by MrJCub** [comment] 2016-04-18 02:51
Are you flying in Auto Level mode?

**Comment by martinbudden** [comment] 2016-04-18 13:34
This looks like a duplicate of issue https://github.com/cleanflight/cleanflight/issues/1946

This will be fixed in 1.13.0. There might be an interim 1.12.2 release to fix it.

**Comment by a6j** [comment] 2016-04-25 06:50
OK. Thank you.

**Comment by a6j** [comment] 2016-04-25 06:52
> Of course in the mode of stabilization. The acro mode, the controller does not control the balance.

**Closed** 2016-04-25 06:52 UTC
