### ISSUE TITLE
Motors start spinning when quitting CLI

### ISSUE THREAD

**Issue by avivik** [cleanflight/cleanflight#442] opened 2015-01-28 20:04 UTC
Quad is connected with USB cable to the laptop, and also connected to a battery.
I was viewing parameters on CLI (didn't change anything), and when I hit the 'disconnect' button in the configurator, the motors started spinning for 2 seconds and then stopped (because the FC was rebooting as a result of quitting the CLI).
I repeated the scenario, and while this phenomenon doesn't happen all the time, it happens ~80% of the time.
This doesn't happen when quitting the CLI the "right" way, by typing 'exit' or 'save'.

Naze32 v1.6.0
Configurator 0.6.0
Windows 7 Pro 64-bit

**Comment by SlyMike** [comment] 2015-01-28 20:49
I had similar issues #385

**Comment by hydra** [comment] 2015-01-29 04:38
Duplicate of #123

**Comment by hydra** [comment] 2015-01-29 04:39
Can you update on #123 with details of which ESCs you are using?

**Closed by hydra** 2015-01-29 04:38 UTC
