### ISSUE TITLE
3D view in configurator freezes with CJMCU

### ISSUE THREAD

**Issue by eziosoft** [cleanflight/cleanflight#353] opened 2015-01-14 00:34 UTC
1. GUI locks up (freezes) from time to time (very often) on the Setup tab. It happens only on the Setup tab.  And the packet error counts up. I recorded a video to show you how it looks like. On the video I'm waving the quad up and down constantly.
Here is the link: http://youtu.be/WSGpiLn9Fiw

**Comment by hydra** [comment] 2015-01-14 00:48
i saw the same thing on my cjmcu v2 the other day too.  Not sure if the problem is with the latest v2 cjmcu hardware or latest configurator.

any chance you could try older combinations of firmware and configurator to try and find out what combination of firmware/configurator was ok and when it started freezing?

**Comment by hydra** [comment] 2015-01-14 00:51
Using the same version fo the configurator other targets like the Naze, EUSTM32 and Sparky were ok.  Have a feeling this is CJMCU specific.  If anyone else sees the same problem please give details of firmware version and configurator version.

**Comment by eziosoft** [comment] 2015-01-14 00:52
as I remember the gui without 3d model (quad) worked well. 
I can see the same issue when I upload baseFlight to CJMCU with baseflight configurator.
And I'm almost sure that it begun when the 3d model replaced a box.

**Comment by eziosoft** [comment] 2015-01-14 00:54
maybe CJMCU doesn't replay on one of the MSP commands ?

**Comment by eziosoft** [comment] 2015-01-28 01:40
any news ?

**Comment by hydra** [comment] 2015-02-23 21:32
Identified and fixed in latest configurator development branch.  It was the addition of the GPS panel to the setup tab that was the cause - CJMCU doesn't have GPS compiled in and thus doesn't respond to the GPS commands that were being issued by the configurator which did not handle it gracefully.

**Closed by hydra** 2015-02-23 21:32 UTC
Labels: bug
