### ISSUE TITLE
channel mapping enhancement

### ISSUE THREAD

**Issue by zatalian** [cleanflight/cleanflight#68] opened 2014-09-09 17:20 UTC
* having more channels than functions, it would be nice to have a map function that can leave some channels unused
* it would be nice to have the possibility to not map a function to a channel

proposed command example:

map ---TREA123------

this maps throttle to the 4th channel, rudder to the 5th, ... aux3 to the 10th channel.
channels 1-3 and 11-16 are left unused

**Comment by hydra** [comment] 2015-05-15 15:57
Unused channels are not a problem for the FC.  I'm not sure what the problem is here.  The `map` command can take `AERT12345678abcdefgh`.

Closing.  If you can provide more information we can investigate further.

**Closed by hydra** 2015-05-15 15:57 UTC
Labels: enhancement

**Comment by MasterZap** [comment] 2016-02-19 12:26
The problem is anything above 4 in the channel mapping string is meaningless/useless, because any aux channels above 5 har "hard mapped" to channels 8 and above. 

I.e. if I write "567TAER1" the actual mapping is

"567TAER156789...." 

This is since the mapping string is only 8 characters, and anything after that 8:th character is never remapped.

The reason you want to have unused channels is for things like the X4RSB, which has SBUS channels (1-16) but then also output channels 1-3 as PWM.

The only way to make that work today is to use "234TAER1" as channel mapping string, and then never actually use AUX 2, 3 or 4 in the FC.

That would be fine, if not some optimizations by Boris et. al. is actually cutting down on the number of AUX channels.

There are many potential fixes to this:

a) Allow a longer mapping string
b) Actually remap the "remaining" channels above 8 to use the channels not used in the mapping string yet automatically.
c) Allow a "not used" string in the mapping string + b

/Z
