### ISSUE TITLE
1.14 + Naze32 rev5 Freezes after arming with Telemetry enabled

### ISSUE THREAD

**Issue by DopeyOne** [cleanflight/cleanflight#2484] opened 2016-11-07 07:34 UTC
When using 1.14 on my Naze32 rev5 with OS125 + PPM + Telemetry (UART1 telemetry set to FrSky @ 9600baud)

If I arm the controller, I can no longer disarm and/or control the motors (looks like the FC locks up)

If I remove the UART1 telemetry configuration, board functions normally when armed

Replicated the same setup on 1.13 and I do not experience the issue.

**Comment by hydra** [comment] 2016-11-07 10:35
please supply config dump and we'll investigate ASAP.

**Comment by DopeyOne** [comment] 2016-11-07 11:38
[114_Naze32_Broken.txt](https://github.com/cleanflight/cleanflight/files/575204/114_Naze32_Broken.txt)
[114_Naze32_Working.txt](https://github.com/cleanflight/cleanflight/files/575205/114_Naze32_Working.txt)

**Comment by DopeyOne** [comment] 2016-11-07 11:41
Very basic/minimal configs...

But if UART1 is set to FrSky @ 9600, then arming the board causes it to freeze.
Disable FrSky Telemetry on UART1 and it doesnt freeze.

FW update was done with full chip erase, so there shouldn't be any legacy configs causing issues.

**Comment by DopeyOne** [comment] 2016-11-07 11:44
[113_Naze32_Working.txt](https://github.com/cleanflight/cleanflight/files/575219/113_Naze32_Working.txt)

Working 1.13 config with Telemetry on UART1

**Comment by Poitivin** [comment] 2016-11-13 02:22
I have the same setup you have and updated today my firmware from 1.13 to 1.14.1 and cannot arm in pid controller multiwii rewrite. LuxFlot arms ok and I have the same exact config between these two pid controllers with the exception of pid values and rc values...

**Comment by martinbudden** [comment] 2016-11-13 04:38
@Poitivin , your issue is a duplicate of https://github.com/cleanflight/cleanflight/issues/2479

**Comment by Poitivin** [comment] 2016-11-13 04:46
Thanks. It seems to be yes. I´ll keep an eye on #2479

**Comment by Ryanpolo** [comment] 2016-11-22 15:08
just wanted to add. i too had this problem. naze32 rev6. using 1.14 at idle was 600% cpu. reflashed to 1.13

**Comment by lackr007** [comment] 2016-11-24 02:31
I can also confirm that this FC lock up issue on 1.14 on 2 different naze32 rev5 + PPM + telemetry + LED. 1.13 works fine.

**Comment by Ahimoth** [comment] 2016-12-12 19:20
Same here. 1.13 works fine with FrSky telemetry enabled on naze32 rev5 and rev6. Updated to 1.14 with full erase and now FC appears to lockup immediately after arming when FrSky Telemetry is enabled. Disable the telemetry and it works fine.

**Comment by hydra** [comment] 2016-12-27 23:11
deleted unrelated comments.

**Comment by hydra** [comment] 2016-12-27 23:34
bug confirmed, issue is with the DMA handler initialisation when the SHARED UART port is re-opened for use as a telemetry port after being already used by MSP.

**Comment by hydra** [comment] 2016-12-27 23:48
fixed with this workaround.

6b7ac227b5c073560f5f0df534e46385ae099f84

**Comment by hydra** [comment] 2016-12-27 23:48
please test 1.14.2 RC3 when available.

**Closed by hydra** 2016-12-27 23:48 UTC
Labels: bug
