### ISSUE TITLE
how to adjust loop time? FC not responding to cycle time changes?

### ISSUE THREAD

**Issue by CreeT6** [cleanflight/cleanflight#2092] opened 2016-04-29 07:13 UTC
i just flashed cleanflight from betaflight, on spracingf3, the default loop time seems to be 1000, i cannot change it via configuration and CLI, what is the problem?

**Comment by lostcontrol** [comment] 2016-04-29 07:32
You have _gyro_sync_ enabled. This is a support question and not a bug report so please, close it. Thanks.

**Closed** 2016-04-29 13:54 UTC
