### ISSUE TITLE
Problem in sonar and oneshot125 esc

### ISSUE THREAD

**Issue by sandeeppahadi** [cleanflight/cleanflight#2719] opened 2017-04-14 05:29 UTC
i have problem with sonar too. even though i turned sonar feature on its not turning into green. Oneshot125 esc is also not working. everything was fine before upgrading. Can anyone give me solution?

**Comment by McGiverGim** [comment] 2017-04-14 05:49
What FC are you using?

**Comment by sandeeppahadi** [comment] 2017-04-14 05:50
i m using spracingF3 delux

**Comment by McGiverGim** [comment] 2017-04-14 05:57
Ok, I've seen that maybe the problem is the same that https://github.com/cleanflight/cleanflight/issues/2717 and that you are aware of that. I think that the only solution is to wait to some developer to solve it and use the 1.x version until then. Let's wait to some developer to see if there's other solution, sorry.

**Comment by sandeeppahadi** [comment] 2017-04-14 06:14
neither 1.x version is working. When I setup previous version It asks to upgade it. I cannot configure with previous version either. I am stucked now. I am using PMW for motors to run cause my motors doesnot run on selecting oneshot125. Everything was fine before upgrading.

**Comment by McGiverGim** [comment] 2017-04-14 06:32
You miss use the older version of the configurator https://github.com/cleanflight/cleanflight-configurator/tree/master_v1.x

**Comment by hydra** [comment] 2017-04-14 14:41
duplicate of https://github.com/cleanflight/cleanflight/issues/2717

**Closed by hydra** 2017-04-14 14:41 UTC
