### ISSUE TITLE
Activate failsafe when using RXs that send the same signal on signal loss

### ISSUE THREAD

**Issue by dave-pitman** [cleanflight/cleanflight#276] opened 2014-12-29 00:28 UTC
## Enhance Failsafe for instances where RX is not configurable to enable Failsafe on FC.

Add an element to the Failsafe family that would trigger Failsafe when no RX commands change within a certain time (seconds).

>(From Failsafe.md)

>The failsafe system is not activated until 5 seconds after the flight controller boots up. This is to prevent failsafe from activating in the case of TX/RX gear with long bind procedures before they send out valid data.

>After the failsafe has forced a landing, the flight controller cannot be armed and has to be reset.

>The failsafe system attempts to detect when your receiver looses signal. It then attempts to prevent your aircraft from flying away uncontrollably.

>The failsafe is activated when:

>Either:

>a) no valid channel data from the RX is received via Serial RX.

>b) the first 4 Parallel PWM/PPM channels do not have valid signals.

>**ADD: c) no variation in RX input for the time specified in failsafe_auto_trigger**

>And:

>c) the failsafe guard time specified by failsafe_delay has elapsed.

## Purpose:
Currently if an RX is not configurable to send no signal if a connection with the TX is lost, it will send the last good signal indefinitely.  Because of this, the Failsafe feature in Cleanflight will never trigger.

### Command
"Failsafe_Auto_Trigger = 50"

### Function
If no RX value changes within the set time frame, then Failsafe will be activated,

Using this example, if the FC saw no movement on any channel of the RX for 5 seconds, Failsafe would activate.  On mini quads, a very small time could be set, and for fixed wing a longer time.

Thanks Guys!

**Comment by hydra** [comment] 2015-01-20 18:00
@HFMan the failsafe activation delay would be used and the user can configure it.  If the aircraft enters failsafe mode using the sticks again should abort the failsafe state.

**Comment by hydra** [comment] 2015-03-03 10:44
this is a duplicate of #112

**Closed by hydra** 2015-03-03 10:44 UTC
Labels: duplicate, enhancement
