### ISSUE TITLE
AUX settings not restored with pasted dump.

### ISSUE THREAD

**Issue by readerror67** [cleanflight/cleanflight#1332] opened 2015-09-21 10:36 UTC
In reference to #1331 
Apparently when the profile is changed just before the aux settings are pasted, it causes a delay in switching profiles (even if you are on profile 0 and pasting a dump that contains 'profile 0').

@hydra mentioned this is due to the lack of flow control which makes sense.

**Comment by SteveAmor** [comment] 2015-09-21 15:10
I believe this is a clean flight configurator issue and should probably be raised there?

**Comment by stronnag** [comment] 2015-09-21 16:17
In my experience aux profiles are restored, even when the profile is changed, *as long as* sufficient care is taken to ensure items are pasted in small batches, with delays to allow the poor old FC to keep up.

**Comment by Arakon** [comment] 2015-09-22 04:14
Whenever you paste anything containing a profile switch in it (i.e. "profile 2"), it takes a brief moment as the FC switches over. Anything pasted in that brief moment gets lost. Best way is to paste up to a "profile x" command, then continue pasting the next section afterwards to give it time to perform the switch..

**Comment by readerror67** [comment] 2015-09-22 07:41
Or the useless profile reference within the dump can be removed per #1331 and things will 'just work(tm)'

**Comment by borisbstyle** [comment] 2015-09-22 10:44
just paste AUX section once more :D

**Comment by hydra** [comment] 2015-09-23 08:59
Duplicate of #325, opened about 1000 issues ago.

**Closed by hydra** 2015-09-23 08:59 UTC
