### ISSUE TITLE
ARM + MOTOR_STOP + Failsafe + No Throttle = Failsafe Throttle

### ISSUE THREAD

**Issue by AlmightyFrog** [cleanflight/cleanflight#987] opened 2015-06-03 22:45 UTC
In version 1.9 I have issue as following:
If copter is armed but no throttle yet applied as per setting MOTOR_STOP, the motors are not spining up.
In case at that time RX connection is lost motors spin up to i guess failsafe throttle even that motors were off before.

Way to reproduce:
(0. Remove props)
1. Turn on Remote
2. Turn on Copter
3. Arm Copter
4. Turn off Remote

Note: Reflashed 1.8. and 1.8.1 for regression test - there is no issue like that.
Note: Using D4R-II in PPM mode, but that should be irrelevant i guess.

**Comment by hydra** [comment] 2015-06-04 08:31
This is by design.  There are other issues that cover this, see #234 primarily.  Closing as duplicate.

**Closed by hydra** 2015-06-04 08:31 UTC
Labels: duplicate
