### ISSUE TITLE
The latest cleanflight development builds 1.9.0 look to have isues booting on some STM32F1 based boards

### ISSUE THREAD

**Issue by MJ666** [cleanflight/cleanflight#810] opened 2015-04-24 13:03 UTC
There are quite some reports that CF will not properly boot on Naze boards. Sometimes it helps to unplug and reapply the power to get it booting. I personally experience this with an Lulfro Brushed FC. An build a couple of days ago was not even booting at all. An actual build will require to reapply power sometimes an second time to boot. The AfroMini32, AlienWii F1 and Flip32+ is not really affected by this problem. I guess the has to do with the introduction of the interrupt code for the MPU6050 (I may be wrong with this).

**Comment by Arakon** [comment] 2015-04-24 17:17
The CC3D also seems to have no problem with it. I only tested 3 or 4 times, but it seemed to boot up fine every time.

**Comment by SteveAmor** [comment] 2015-04-24 17:23
It would appear that this issue became present in commit 6d5b44df7af32d194448c57a99f2d0af02d89f27 on a Naze 32 acro (AfroFlight 32 Rev5).

It appears to be a timing issue.  If the board has been powered down for more than 10 seconds, connecting 5V to the receiver pins will result in a failed boot.  If you disconnect the 5V and reconnect within a couple of seconds, the board will boot correctly.  If you have a receiver connected, you have to power cycle really quickly to get it to boot and it usually takes several attempts.

I can't replice this issue when powering via the USB port.  It boots correctly every time.

Reverting to commit d3d9721e9195f40752d7aa2cdefe6923fb1c5426 (which is the first, earlier commit that enables the board to boot at all) does not exhibit this issue.

**Comment by dascons** [comment] 2015-04-25 04:36
I have a CC3D and it seems to be affected by this issue as well.
Also a potentially related issue is that it doesn't connect to the
configurator unless powered by battery (This is not an issue with stock FW)

**Comment by MJ666** [comment] 2015-04-25 07:44
This is alse the behavior I also have seen with the Lulfro board.

**Comment by hydra** [comment] 2015-04-25 09:12
@St7ven when your board fails to boot what do the leds to, a video would be helpful here.

**Comment by hydra** [comment] 2015-04-25 09:16
Can you also please use git biset to find the EXACT commit that introduced the problem.

http://git-scm.com/docs/git-bisect

**Comment by SteveAmor** [comment] 2015-04-25 10:37
In this case, the video won't be very exciting and the power LED  is so bright it over exposes the camera so it's difficult to see the other LEDs.  On power up, the power LED lights immediately and less than a second later, L1 (my green led) lights and stays solid.  L0 does not light up (my red led) at all.

If you need me to, I can connect a logic analyser or analogue scope to L1 but I'm pretty sure it's permanently lit (i.e. 100% duty cycle).

I'm struggling with git bisect as there is the bug that stopped my board booting up in the middle of the commits it's asking me to check.  I'll keep working on it.

**Comment by SteveAmor** [comment] 2015-04-25 14:19
It's impossible to find the EXACT commit that has introduced thisbug as I am having to git bisect skip whenever I hit bug 774 that prevents the board from booting up at any time.   The git bisect algorithm isn't closing in on the issue as I have to keep skipping.

**Comment by nebbian** [comment] 2015-04-25 15:17
I know that I had problems with versions that were compiled just after 1.8.1 was released.  I was trying to use it to do testing on a new proximity system, and I know that it wasn't booting at all.  I tried several versions, but going back to 1.8.1 fixed the problem.
Just tonight I tried the latest build from source, which also booted fine.  
I'd suggest that the bug has now been resolved.

**Comment by SteveAmor** [comment] 2015-04-25 16:25
The problem where the board won't boot at all has been resolved (bug 774).  However, this is a different problem and it is still present in the latest build.  The board boots ok from USB but takes several attempts from external 5V supply.

**Comment by ethomas997** [comment] 2015-04-27 08:23
Tonight when I first powered up my Naze32 Acro it exhibited this issue -- froze during boot with green LED lit. After a power cycle it booted OK, and doing a few more power cycles did not reproduce the issue. Was running with power from 5V on the pins (not USB), transmitter off; code was at commit 1d069ad.

--ET

**Comment by SteveAmor** [comment] 2015-04-27 09:14
I can repeat this issue by waiting at least 10 seconds before applying power.

**Comment by JurikRistjouw** [comment] 2015-04-27 16:03
I also have this issue.
- when connecting to USB (beeper starts to chirp like a cricket indicating low voltage and no tx)
- when connecting usb+power, everything boots and is good
- when connecting power only after disconnect, not booting / no tx response, not arming

**Comment by Spirre** [comment] 2015-04-28 06:22
Also got the problem on Naze32, running the latest build with MJ666 G-tune code. When it happens for me the ESC tunes comes out of sync and blue and green led are solid. A few more tries and it works. Only get this when I connect the battery, never happens when I just use USB.

**Comment by SteveAmor** [comment] 2015-05-01 19:01
I ran a git bisect but had to skip all the commits between commit d3d9721e9195f40752d7aa2cdefe6923fb1c5426 (good) and commit 6d5b44df7af32d194448c57a99f2d0af02d89f27 (bad) so it reported that a shed load of commits were possible first bad commits.  I decided on a different approach given I was convinced that the issue was introduced in 6d5b44df7af32d194448c57a99f2d0af02d89f27.  So I commented out 
#define USE_MPU_DATA_READY_SIGNAL https://github.com/cleanflight/cleanflight/blob/master/src/main/target/NAZE/target.h#L74 and my AfroFlight rev5 now boots every time when connecting 5V.
Just to reiterate, there is never a boot problem when powering via USB.  It only happened after leaving the board for down powered for more than 10 seconds and then powering up with an external 5V.

**Comment by Spirre** [comment] 2015-05-01 20:18
Seems like a timing issue, so it's the extra delay that mess things up, or?

**Comment by SteveAmor** [comment] 2015-05-01 21:33
It does look to be a timing issue.  When I was in the field, the issue was 100 times worse.  With a receiver and escs connected, I really had to be very quick with my power cycles to get it to boot correctly.  I put it down to the Spektrum rx and/or BEC at the time but it's clearly not that (and 1.8.1 didn't have this issue with my fully built tricopter).

**Comment by Spirre** [comment] 2015-05-01 21:55
I was doing some tests today and i got it almost every time I connected the battery for the first time. Quite easy for me to notice if it didn't initialize, the LED's wouldn't go on. Unplug directly and plug it in again and it usually worked. I not 100% sure but I believe that I also got it when I just connected the USB.

**Comment by JurikRistjouw** [comment] 2015-05-02 00:04
@SteveAmor thanx, i will test this and report.

**Comment by Spirre** [comment] 2015-05-02 08:26
I've comment out the delay(50); from line 81 in hardware_revision.c and did some tests and no problem so far :)

**Comment by hydra** [comment] 2015-05-03 15:08
are you guys using naze full or acro boards?

**Comment by SteveAmor** [comment] 2015-05-03 15:12
Acro.

**Comment by stronnag** [comment] 2015-05-03 16:16
This only happens for me on the Mullet Acro board. Full naze and flip32/flip32+ do not exhibit the problem.

**Comment by MJ666** [comment] 2015-05-03 17:02
Have problems with the Lulfro Bushed board. AlienWii F1 and Flip32+ looks to be not affected. My Naze, MW32 are not tested yet.

**Comment by Spirre** [comment] 2015-05-03 17:06
Acro board. Seems like the temperature makes a difference. When I tested on the bench I usually don't have the problem, but when I got out last evening it was almost impossible to get it to initialize. But today   it was warmer and it only happened a couple of times. I can get it also when I plug in the USB, but that is not very often.

**Comment by SteveAmor** [comment] 2015-05-03 17:30
I just freezer sprayed my board and it made no difference.  However, I think I have found the problem.  Comment out the following i2cWrite (to a read only register so this line needs to be removed anyway):

https://github.com/cleanflight/cleanflight/blob/a5c2c705417c0f771edd0312a8ef9a72466a1c82/src/main/drivers/accgyro_mpu6050.c#L434

**Comment by stronnag** [comment] 2015-05-03 17:35
With the Acro Mullet, consistently requires power on / off / on to boot. Just a momentary initial connection (to the first ESC chime), disconnect, reconnect is enough. If I don't go through that dance sequence, this particular board will never boot first time on 1.9.

**Comment by hydra** [comment] 2015-05-03 17:56
Its possible the int handler is configured and enabled to early after telling the 6050 to generate data ready signals on the int pin.  I will try and find a board that exhibits the same behaviour.

**Comment by hydra** [comment] 2015-05-03 18:01
@SteveAmor the register is Read/Write. See page 27ofthe mpu6050 reference manual.

**Comment by SteveAmor** [comment] 2015-05-03 18:24
Ooops, I was looking at the INT_STATUS register.

I moved configureMPUDataReadyInterruptHandling() to the end of mpu6050GyroInit and it made no difference.

**Comment by SteveAmor** [comment] 2015-05-03 18:33
Adding a delay doesn't work either.  However, it does exhibit a slightly different problem, only the power light comes on now.  

#ifdef USE_MPU_DATA_READY_SIGNAL
    i2cWrite(MPU6050_ADDRESS, MPU_RA_INT_ENABLE, MPU_RF_DATA_RDY_EN);
#endif
    delay(100);
    configureMPUDataReadyInterruptHandling();
}

**Comment by SteveAmor** [comment] 2015-05-03 21:30
I would do a PR but it's late and as this is a critical bug, I believe the fix is as follows (essentially, moved the chip id read to the beginning and return false is no ack).

bool bmp085Detect(const bmp085Config_t *config, baro_t *baro)
{
    uint8_t data;
    bool ack;

    if (bmp085InitDone)
        return true;

    delay(20); // datasheet says 10ms, we'll be careful and do 20. 

    ack = i2cRead(BMP085_I2C_ADDR, BMP085_CHIP_ID__REG, 1, &data); /* read Chip Id */
    if (!ack)
        return false;

#if defined(BARO_XCLR_GPIO) && defined(BARO_EOC_GPIO)
    if (config) {
        EXTI_InitTypeDef EXTI_InitStructure;
        NVIC_InitTypeDef NVIC_InitStructure;
        gpio_config_t gpio;

        bmp085InitXCLRGpio(config);

        gpio.pin = config->eocGpioPin;
        gpio.mode = Mode_IN_FLOATING;
        gpioInit(config->eocGpioPort, &gpio);
        BMP085_ON;

        registerExti15_10_CallbackHandler(BMP085_EOC_EXTI_Handler);

        // EXTI interrupt for barometer EOC
        gpioExtiLineConfig(GPIO_PortSourceGPIOC, GPIO_PinSource14);
        EXTI_InitStructure.EXTI_Line = EXTI_Line14;
        EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
        EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
        EXTI_InitStructure.EXTI_LineCmd = ENABLE;
        EXTI_Init(&EXTI_InitStructure);

        // Enable and set EXTI10-15 Interrupt to the lowest priority
        NVIC_InitStructure.NVIC_IRQChannel = EXTI15_10_IRQn;
        NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = NVIC_PRIORITY_BASE(NVIC_PRIO_BARO_EXT);
        NVIC_InitStructure.NVIC_IRQChannelSubPriority = NVIC_PRIORITY_SUB(NVIC_PRIO_BARO_EXT);
        NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
        NVIC_Init(&NVIC_InitStructure);
    }
#else
    UNUSED(config);
#endif 

    bmp085.chip_id = BMP085_GET_BITSLICE(data, BMP085_CHIP_ID);
    bmp085.oversampling_setting = 3;

**Comment by ledvinap** [comment] 2015-05-04 07:31
@SteveAmor : Yes, good catch.

When baro is not detected, unregisterExti15_10_CallbackHandler is called and handler removed, but EXTI is not disabled. After first rising edge on Baro pin EXTI interrupt is called indefinitely... Input is floating, everything is OK if it gets high before EXTI is setup ...

**Comment by SteveAmor** [comment] 2015-05-04 08:14
Doing PR right now

**Comment by SteveAmor** [comment] 2015-05-04 08:49
https://github.com/cleanflight/cleanflight/pull/836/files

**Comment by stronnag** [comment] 2015-05-04 10:35
Tested. Fixes my Acro Mullet, thanks.

**Comment by hydra** [comment] 2015-05-06 12:05
Thanks for the update @stronnag

**Comment by hydra** [comment] 2015-05-06 12:08
Fix merged, closing.  Please re-open if there are further issues.

**Closed by hydra** 2015-05-06 12:08 UTC
Labels: bug, critical
