### ISSUE TITLE
Flip32 (Naze32 rev4) not arming since CF1.12

### ISSUE THREAD

**Issue by joehallenbeck** [cleanflight/cleanflight#2181] opened 2016-05-29 20:48 UTC
We're having problems arming two Flip32 boards since Cleanflight 1.12
Everything works as expected with 1.11-NAZE, but with 1.12 arming through the RC causes the FC to beep correctly, but throttle doesn't work. The same goes for 1.13RC1 with the exception that a software reset (just switching to the CLI tab and back without any changes) causes all motors to spin without arming them!

Hardware used: EMax MT2204 + EMax mini ESCs, Flip32 10DOF (a.k.a NAZE32 rev.4).
We've experienced these problems on two seperate copters. No problems whatsoever with one using a SPF3Mini and CF 1.12

Problem also persists with Betaflight 2.6.1 to 2.8.0 - arming causes FC to beep as expected but throttle doesn't power up the motors. No problems on SPF3Mini.

**Comment by joehallenbeck** [comment] 2016-05-29 21:08
We've got lab equipment locally available for analysis if needed (oscilloscope, function-generator, etc.), but it seems to be a software issue since everything works well after downgrading to CF 1.11

**Comment by lechak** [comment] 2016-05-30 07:32
Maybe you using luxfloat pid controller. Same issue with naze32 rev6
Try search here https://github.com/cleanflight/cleanflight/issues/2091
or here:
https://github.com/borisbstyle/betaflight/issues/110
Or try other pid controllers. MWrewrite work fine

**Comment by martinbudden** [comment] 2016-05-30 07:53
@joehallenbeck 

This is not a bug, it's deliberate behaviour. Cleanflight now has a check to disable arming if the board is overloaded, see:

https://github.com/cleanflight/cleanflight/blob/master/src/main/mw.c#L263

Previously the board could arm, but this could then cause problems in flight.

**Comment by martinbudden** [comment] 2016-05-30 18:08
Duplicate of https://github.com/cleanflight/cleanflight/issues/2091

**Closed** 2017-02-25 16:57 UTC
Labels: duplicate
