### ISSUE TITLE
SPRACING32/NAZE32 - Add support for MPU6050 data ready interrupt - Prevents Afroflight booting

### ISSUE THREAD

**Issue by SteveAmor** [cleanflight/cleanflight#776] opened 2015-04-15 20:29 UTC
commit c11c25514b4d4b71eb6affc6d7e01cf4014e91f3
SPRACING32/NAZE32 - Add support for MPU6050 data ready interrupt
When flashed onto an Afroflight Rev5, it will not boot up.  Need to short bootloader pads to reflash.

Previous commit (c8a33ab1dbadfa4bfc1e64a70dfbbae5ecc24392) works fine.

Compiled on Ubuntu 14.04 64-bit with gcc-arm-none-eabi=4.9.3.2015q1-0trusty13 from Terry Guo.

**Comment by stronnag** [comment] 2015-04-15 20:30
https://github.com/cleanflight/cleanflight/issues/774

**Comment by SteveAmor** [comment] 2015-04-15 20:57
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150303 (release) [ARM/embedded-4_9-branch revision 221220]

**Comment by hydra** [comment] 2015-04-16 01:00
Duplicate of #774

**Closed** 2015-04-16 01:03 UTC
Labels: duplicate
