### ISSUE TITLE
Unable to save servo settings CleanFlight 1.9.0 Tricopter mode

### ISSUE THREAD

**Issue by palanthas** [cleanflight/cleanflight#1273] opened 2015-08-29 21:37 UTC
When setting YAW to reversed mode I am unable to save the settings. After hitting save in cleanflight configurator, changing to another tab and back YAW is set back to Normal.

This is CleanFlight Conf. 0.65.0 in Chrome on Linux Mint 17 64bit

**Comment by palanthas** [comment] 2015-08-29 21:47
Save does work in 1.8.1 however.

**Comment by mykhanpk** [comment] 2015-08-30 05:12
v1.9.0
Same issue, Unable to change any parameter in servo tab and everything works well in 1.8.0 or 1.8.1

Secondly restore from file also don't show any updates but values are set after two or more tires without any reboot to controller.
Cleanflight 0.65 and windows 8.1 64bit.

**Comment by SteveAmor** [comment] 2015-08-30 08:10
Duplicate of #991

**Closed** 2015-08-31 01:45 UTC

**Comment by nathantsoi** [comment] 2015-08-31 06:47
just ran into this setting up my tricopter + flip32. see https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#servo-reversing

running this in the cli fixed it for me: `smix reverse 5 2 r`

btw, `5` is weird, since I'm running my servo on `S1`...
