### ISSUE TITLE
Update Mixer.md 

### ISSUE THREAD

**Issue by madwasp** [cleanflight/cleanflight#587] opened 2015-03-04 19:12 UTC
There is no detailed information about the roll, pitch and yaw when defining a custom mixer in terms of the signal - or + .

It should exist more information in the Mixer.md documentation about how to know if the value of each motor roll/pitch/yaw should be positive or negative while defining a custom mixer.

The is allot of contradictory information in the internet forums and not easily to understand.

**Comment by hydra** [comment] 2015-03-04 20:47
Duplicate of #253 - please search before creating new issues.

**Closed by hydra** 2015-03-04 20:47 UTC
