### ISSUE TITLE
Can't save feature RX_SERIAL without serial port scenario

### ISSUE THREAD

**Issue by twokaff** [cleanflight/cleanflight#279] opened 2014-12-30 01:35 UTC
Removed my previous comment and make this a suggestion instead. ;)

Unless you dive into the Wiki there's no way of telling that you can't enable RX_SERIAL without configuring a serial port scenario first.

A link, pop-up, whatever in the GUI would be nice to advise the user of this.

**Comment by twokaff** [comment] 2015-01-03 23:43
Great to have the Port tab in the latest configurator.  Many thanks!

The issue remains though, that you have to configure at least one port to scenario 3 before you can enable RX_SERIAL.

Would it be possible to also enable RX_SERIAL when scenario 3 is set on one of the ports?  Is there are situation where that would not be desirable?

**Comment by hydra** [comment] 2015-01-17 19:23
The port configuration tab could probably be updated.  It's simple at the moment to allow it to function.

The problem is if you move the feature configuration from the configuration tab it's not obvious when you have conflicting features either.  It's kind of a catch 22.

If you have any suggestions on how to lay out the UI better i'm all ears but i don't think blindly enabling features is the right answer here.  The same applies to the GPS feature too.

**Comment by hydra** [comment] 2015-01-17 19:25
I will close this since it's expected behavior, if you come up with a different idea please comment and re-open the issue.

**Closed by hydra** 2015-01-17 19:25 UTC
