### ISSUE TITLE
IO - Turnigy 6A ESC compatibility issue - exiting CLI causes motors to run briefly

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#123] opened 2014-10-18 20:18 UTC
Consider the following:

* I connect to the FC via BT, requiring it to be powered by LIPO;
* The TX is powered off, the machine is **NOT armed**;
*  I set `feature FAILSAFE`;
* I invoke `save`, either explicitly or by navigation to a different tab in the web UI;
* The FC reboots and **briefly runs the motors at failsafe levels** until it realises it's not armed and should not have done that, so the motors stop;
* The poor user bandages their bloodied fingers [0].

A more describable outcome would be that the FC never runs the motors unless explicitly armed, regardless of failsafe. 

[0] OK, this is pure melodrama, but it makes the point.

**Comment by dave-pitman** [comment] 2015-01-29 05:07
Just wanted to add that this has happened to me, although I did not make note at the time what exact sequence caused it.  In fact I'll admit to not knowing that is should not happen.  From now on, I will pay more attention.

I'm using a Naze32 clone with Emax 12a simon series escs running blheli firmware.

**Comment by avivik** [comment] 2015-01-29 06:46
This happened to me when I was in the CLI window and pressed the 'disconnect' button in the configurator (issue #442 ).
I'm using Emax 12A ESC with blheli FW (Simon Series)

**Comment by dave-pitman** [comment] 2015-01-30 01:36
I just had a motor spin-up incident.

Made some changes to adjustment ranges in the CLI and when I clicked <enter> after typing save, the motors spun up for about 1/2 second.  FC and ESCs listed above.

**Comment by fiveangle** [comment] 2015-01-30 03:42
Perhaps unrelated to this bug, I was configuring in CLI when the phone range and I jumped up to get it, accidentally disconnecting the serial line.  I left it be and a few seconds later during my call, I heard the motors (props were off) spin up for about 1/2 a second.  Flip32+, 1.7.0 RC. KISS 18A ESCs.  I'll update here if I can get recipe to repro that is different ones already posted here.

-=dave

**Comment by tricopterY** [comment] 2015-02-02 23:18
Just to add to this discussion: I have Naze32 (HK Rev 5) running Baseflight on a mini spider hex, and randomly get one motor spin up even if the FC is not Armed (ESCs are unbranded 30Amp SimonK flashed). The root cause is something to do with HardFault_Handler. Something triggers that, and it invokes writeAllMotors(MIN_COMMAND). Most ESCs ignore values lower than 1000, but if they don't and are initialised, when as low as 900, you will get a spin up. A glitch in power supply or noise could be a cause.

**Comment by hydra** [comment] 2015-02-16 23:13
Please re-test with latest code from master branch - PWM initialisation delay has been reduced.

**Comment by hydra** [comment] 2015-02-16 23:19
Also of note, and possibly related - I had an issue where a Kiss 12A ESC stuttered on startup and brielfy spun up for a small period of time.  This was resolved by recalibrating the ESC and it has never done it since.  It happened about 1 in 10 times from cold start from battery, not by exiting the CLI.  No USB cable was connected either.

**Comment by stronnag** [comment] 2015-02-18 20:14
Retested 1.7.2 pre-release with a stress test:
```
$ cf-cli -d /dev/rfcomm2 pink-neb_merged_merged.txt 
19:43:52 Reboot on defaults
19:43:52 Rebooted ...
19:43:52 Replaying pink-neb_merged_merged.txt
19:44:19 Setting profile 0
19:44:20 Reboot on save
19:44:21 Done
```
motors ran up during both reboot sequences. Recently calibrated ESCs. BT, so no USB involved.

**Comment by hydra** [comment] 2015-02-19 21:40
Ok, thanks for the update stronnag.

**Comment by hydra** [comment] 2015-02-23 14:03
I made some changes in this commit:

b9e1283809ec97353722f7b85ce7e5481e035259

Please can people try a build with that code, re-test and update this issue?

**Comment by hydra** [comment] 2015-02-23 14:06
@stronnag When you last tested, do you recall if the motors span up for a shorter period or time when you tested before ( https://github.com/cleanflight/cleanflight/issues/123#issuecomment-74939039 )

**Comment by stronnag** [comment] 2015-02-23 16:37
Tested:
# Cleanflight/NAZE 1.8.0 Feb 23 2015 / 16:32:26 (b9e1283)

Same effect, motors run each time CLI is exited.

I can't honestly recall if the duration is shorter.

**Comment by ummagawd** [comment] 2015-03-26 20:33
This is happening on my protoype vortex quad. The OSD allows for looptime and PID controller changes, but it does an FC reset when i leave that menu. When that happens, the motors spin up for a brief second. FS value is enabled but at a value = 1000 (not enough to spin the motors, ESC is looking for around 1100 in my case before it spins) in case that helps.

I can also replicate this when plugged in via USB and exiting CLI in the config app.

**Comment by atomiclama** [comment] 2015-05-12 07:05
I can reliably reproduce this when I save from the CLI. 
I'll try and find some time to get some logic traces of the PWM during the save reboot period. 
Currently running 
# version
Cleanflight/NAZE 1.9.0 May 11 2015 / 17:43:46 (4ec28b8)

**Comment by atomiclama** [comment] 2015-05-18 11:29
So what value of set "min_command" are people running ?
One config from above has 900.
my problem stems from using a pwm range from 18us to 2000us the initialisation is hard coded to 1000us and so causes a my motors to spin up for ~1sec. 
I have modified the code and it has fixed my problem.
Pull request? or do other people need to test it?

**Comment by tricopterY** [comment] 2015-05-18 21:47
I set min_command = 1000, min_throttle = 1050, (motor_stop is enabled too) and re-calibrated ESC throttle range (moved throttle stick to lowest position slowly). The random spin ups seem to have gone.

**Comment by hydra** [comment] 2015-05-19 15:04
Please re-test the latest development build that includes the change from #914 - 713e138c4296b32c5f497b45467589fe7573e0ac

**Comment by hydra** [comment] 2015-05-29 22:44
Please test and re-open if not fixed.

0c1a6c5c2fbe6d6d4b649744ba876d9e103156f9 e6733b4dfccf8a32c297f8ccdd214ae3e1619a55

**Closed by hydra** 2015-05-29 22:44 UTC
Labels: bug
