### ISSUE TITLE
HoTT - Improve telemetry receiver compatibility.

### ISSUE THREAD

**Issue by johnlenfr** [cleanflight/cleanflight#260] opened 2014-12-25 21:59 UTC
Hi,

I try to test the telemetry with Hott protocol but doesn't seems to work.
In the CLI I defined:
feature VBAT
feature TELEMETRY
set telemetry_provider = 1

My Graupner MX20 radio have the v1.173 firmware.

I tried different hardware and software combinations, but it won't work.

So I wonder if it is not because of the automatic detection of sensors since last Graupner Firmware of the radio?
The radio ask for modules by (80 8x) and wait for answers (for example, 80 8D for the General Air module).
The one who answer is activ.
This occurs only at the power on.
So, if the telemetry is set after power on, the Hott module General Air is not detected by the receiver and the radio, and nothing happens. I can't see if it is OK with the hott.c code because I don't understand.

So I would like to know if someone could test it and if I'm the only one in this case?
Would like to know if someone could help me with that?

**Comment by Pierre-A** [comment] 2015-01-02 16:32
text mode on the way...
![img_1791](https://cloud.githubusercontent.com/assets/8274225/5597596/50e30f44-92a5-11e4-8198-b8ae881e8d2b.JPG)

**Comment by johnlenfr** [comment] 2015-01-02 17:04
Great!

So, some more tests coming soon for me!

**Comment by hydra** [comment] 2015-01-02 19:07
Nice @Pierre-A looking forward to seeing a PR for this.

@Pierre-A will you have changes based on the timing observations that were made above in your code?

**Comment by Pierre-A** [comment] 2015-01-03 09:07
this one is better...
![happy](https://cloud.githubusercontent.com/assets/8274225/5601983/b20e12c8-932c-11e4-9e96-b932bd0cff4d.jpg)

**@hydra** : in order to have binary and text modes simultaneously, I had to disable the workaround introduced in the *hottCheckSerialData* procedure due to a timing/sync. in serial reading.
Remember : the request byte is 0x80 for binary mode and for text is 0x7F ... when the first byte is 0x80 it is returned as 0x00 while when it is 0x7F, it is read as 0x7F. A subtle issue on reading the first bit of this first byte ?
So I introduced an if condition to account for the case where 0 is returned (not really satisfied with that) and the case where no sensor is detected (emitted by the TX but with no signification for CleanFlight). This last is observed with RX-GR12L in the initialisation steps and explains why it could not work with the previous workaround code.
    if (requestId == HOTT_TEXT_MODE_REQUEST_ID)
    	processTextModeRequest(address);
    else
    if ((requestId ==  0) ||  (requestId == HOTT_BINARY_MODE_REQUEST_ID) || (address == HOTT_TELEMETRY_NO_SENSOR_ID))
    	processBinaryModeRequest(address);

**Comment by johnlenfr** [comment] 2015-01-04 19:53
First tests with GR12L are OK.

@hydra : firmware is cleanflight 1.4.0 with improvements of @Pierre-A 

And Lipo Alarm is OK too: http://www.youtube.com/watch?v=JaI9wcXQASg

- GR12L is on RX_SERIAL
- Telemetry is on SOFTSERIAL2

The only thing is I lost LED_STRIP by enabling SOFTSERIAL, but priority is battery.
I will put a simple led strip.

**Comment by wildflyer** [comment] 2015-01-04 20:32
wow great, I will try that right now :-). how do you set the low voltage to a custom value ?

**Comment by wildflyer** [comment] 2015-01-04 20:55
ok, I updated to 1.4, but how can I change to a custom voltage value for the alarm to test ?

**Comment by johnlenfr** [comment] 2015-01-04 21:51
It is not implemented yet in the official version.
Please be patient, changings are on the way.
Pierre-A have still a lot of work to do, and we have to do some real tests flying before update.

For now I made a change for beeping when we're under the "batteryWarningVoltage", but these changes are not availables.

**Comment by wildflyer** [comment] 2015-01-04 21:55
ok, if I can help, pls send me new versions for testing, if you like :-) ... I have a gr-16 receiver connected via softserial1.

**Comment by wildflyer** [comment] 2015-01-04 22:00
today I made some flights and the gps data was logged to the sd card! :-) ... but not all flights were logged correctly ... eam still was not logged in any flight ... just for your info ... when is it logged and when not ? does the gps start logging only if there is a gps fix ?

**Comment by johnlenfr** [comment] 2015-01-04 22:18
Don't know why but logging doesn't work for me too, for now.
Maybe we have to setup the Radio correctly.

**Comment by wildflyer** [comment] 2015-01-04 22:44
ok :-) ... if you like, send me files to test, I have vbat and gps module connected, a gr-16 and a lot of experience with this system and I am ready to test :-) ... reliable logging of the gps pos, display of baro altitude and mag direction and a reliable alarm for vbat would be my wishes :-)

**Comment by CopterFail** [comment] 2015-01-09 16:45
I'm really looking forward to the text based HoTT telemetry.
I'm trying to use HoTT telemetry on the CC3D for some time now. Mx12 & GR12L.
I took the setting from an example in serial.md:

e) PPX RX, HoTT Telemetry via UART2:
feature FAILSAFE
set serial_port_1_scenario = 5
set serial_port_2_scenario = 4
set telemetry_provider = 1 

After save & reboot the serial_port_2_scenario is reset. Is there a way to get a hint what is going wrong? The 2nd serial port is exclusive for the telemetry and should not conflict with the led_strip.

**Comment by johnlenfr** [comment] 2015-01-09 18:03
did you also set feature VBAT?
serial_port_2_senario is reset to 0?

But you should have some problems with FW 1.5.0 of Cleanflight because in the actual FW the GR12L is not detected fine by cleanflight.
So, even if your telemetry is correctly set, you will receive nothing.
We are currently changing it and new version of the Hott protocol is not available for now.

**Comment by CopterFail** [comment] 2015-01-10 08:10
Serial_port2_senario is reset to 0. 
Yes VBAT and LED_STRIP is also set. The first step is to enable the telemetry.
For my car project, I took the hott Telemetrie from taulabs,works fine with the gr12l , but has no working text mode ...

**Comment by johnlenfr** [comment] 2015-01-10 09:09
Ok, I don't know if on the CC3D you can enable LED Strip and SOFSERIAL at the same time but try to disable LED STRIP, enable SOFTSERIAL and then set your port senario.
There might be a problem with the LED STRIP enabled.

**Comment by CopterFail** [comment] 2015-01-10 09:58
It is not a softserial, its real hardware. Softserial and led_strip is not compatible.

**Comment by wildflyer** [comment] 2015-01-16 10:32
any progress ?

**Comment by johnlenfr** [comment] 2015-01-16 12:59
No, project is in standby for now. Pierre-A is not available at the moment.
But we will be back soon as we can.

**Comment by wildflyer** [comment] 2015-01-18 02:48
ok, I just tested normal hott telemetry with a gr12sh+, it is working well also(display of vbat etc). now I tested with gr-12, gr-12l, gr-16 and gr-12sh+. all receivers are working equally well.
I just need an alarm for the voltage, not just the display :-)

**Comment by CopterFail** [comment] 2015-01-18 11:49
What software version do you use - I've still no success with todays master checkout. CC3D & gr-12l, telemetry is on the 2nd hardware usart. Ports can now be setup. But I do not see a sensor in the mx-12.

**Comment by wildflyer** [comment] 2015-01-18 21:22
hi,

I tested with the version that was up to date about 3 weeks ago, dont know the exact version number. but the receivers are all reacting the same, with the newest software they are all the same, at least the ones I tested.

greetings

joachim

**Comment by Pierre-A** [comment] 2015-01-26 08:26
Hi guys,
coming back...
text mode is coming too but thanks for your patience. I'll open a PR in a while.
Here is a first view with editable items for alarm battery. More to come with editable PIDs.
![hott text mode](https://cloud.githubusercontent.com/assets/8274225/5896878/57d20e72-a53d-11e4-987d-dce3a7bbda80.jpg)

**Comment by johnlenfr** [comment] 2015-01-26 09:36
Hi Pierre,
Very nice job!
I look forward to see more!

Some small remarks you could change at the end:
- would be nice to set the alarm value between 0.00v to 4.2v (well, a lot of people will set a value between 3.0v to 3.5v), so the GUI variable "Warning cell voltage" will be the same as in the Hott Text page.
- would be nice to set the delay between radio alarms (alarm repeat between 0 to 60s?).

;)

**Comment by wildflyer** [comment] 2015-01-27 01:15
hi pierre,

editable pids ? are you crazy ? :-) thats would be a revolution!

how can I get a binary, where I can test the battery alarm ? I would need that asap, if possible :-)

greetings

joachim

**Comment by CopterFail** [comment] 2015-01-28 15:28
Hi, I'm still not able to get the HoTT telemetry working on my CC3D with GR12S. The GR12S is connected to the flexi port (up to v1.7.0 it was port 2 , now it's port 3). 
While debugging the communication line I see the receiver requesting data ( 0x7F, 0x0F every 800ms) but there is no response from the fc. To ensure the tx line is working, I've tested mwc telemetry on this port - it works fine. Has anybody tested HoTT with the flexi port of the CC3D? Or did I miss anything?

**Comment by CopterFail** [comment] 2015-01-29 18:16
Ok, I've 2 GR12S with different firmware,  V3.55 starts requests with 0x7f as mentioned above. The other GR12S did not show a version (prior V3.54 ...) starts request with 0x80. 
The newer firmware requests text_mode (see message above, not yet supported by cleanflight) and the older one requests binary_mode. 
I'm really looking forward to Pierres version ...

**Comment by Pierre-A** [comment] 2015-02-01 17:29
hi guys,
sorry for these last silent days.. it's flu season over there...
@wildflyer , probably not a revolution, just time and coding...:wink:

So, here are the latest news...
I almost finished coding for interactive text mode, so that one can edit the value of parameters presented on the display of the HoTT-TX (MX20 for me).
Up to now I designed 2 pages as shown below :
- for EAM page : lines 2 to 5 are displayed measurements; lines 6 and 7 are editable items (example for the TX alarm beeper).
- for PID page : the PID and Rate profiles can be accessed (example for PIDprofile selection) and the whole numerical values modified. 
The TX arrows and set/esc buttons are used as usual for switching between pages and items, and for selecting/modifying editable items.

After modified, the new values are directly applied to the current configuration.
I have yet to code the EEPROM writing corresponding procedures (the save button is already active).

I will open a PR asap, but in the meantime I can provide a .hex version for testing (no eeprom writing). But please, don't try editing while flying...
So far I tested the code for 3 configurations : 
    - (Naze32 + GR16)  and  (CC3D + GR16) : everything works fine. Did not take time for testing with GR24 but should work.
    - (Naze32 + GR12L) :  the EAM page is there but disappears (sync pb with the GR12L ?). Have'nt digged that yet. @CopterFail, would be interesting to be tested on your GR12S.

Of course comments and suggestions are welcome as these first two pages are only examples of what can be done (no real limitation for any other designs).
![eam page](https://cloud.githubusercontent.com/assets/8274225/5992770/6793c9e6-aa37-11e4-8ca2-456e872b93f3.jpg)
![pid page](https://cloud.githubusercontent.com/assets/8274225/5992696/1ca43964-aa34-11e4-9d87-b57d7c73f79e.jpg)

**Comment by wildflyer** [comment] 2015-02-02 12:47
pierre, this IS a revolution! :-) this is by far the best necessary improvement of displaying and editing data. no more usb cables, laptops, handy apps or bluetooth :-).

is it possible to display gps, mag and baro readout also ? that would simplify testing the gps features in cleanflight.

please give me the hex file to test (cf1.6 or above), I have a gr-12sh+ receiver connected. where can I download ?

greetings from munich :-)

joachim

**Comment by hydra** [comment] 2015-02-02 13:56
I will need to look at the code for this.  I'm thinking that it should be possible to use the same screen based code for the hott telemetry menus as well as for editing pids, etc, via the oled display.

**Comment by ledvinap** [comment] 2015-02-02 13:59
It should be possible to add similar functionality to taranis openTx. I can probably do it if it seems reasonable.

**Comment by Pierre-A** [comment] 2015-02-02 16:58
no problem guys,
I have to finish a few things before opening a PR (asap) and you can play with.

**@hydra**, the TextMode needs the PR≠428 to be merged (workaround process for binary mode is no more needed and text mode needs to be detected). Can you look at it plz ?

Since my last post : 
    - text mode works with GR12L (ambiguity between EAM and Receiver requestIDs in the Rx fw)
    - text mode is now available behind the "Receiver" tab.
    - EEPROM writing works fine (quite obvious with the  *saveConfigAndNotify*), so values edited with the TX can be later recovered under CLI.

**Comment by wildflyer** [comment] 2015-02-02 21:27
ok, great, cant wait :-)

is it possible to make the alarm in 1/100 voltage-steps ? for example:alarm below 10.85V

**Comment by johnlenfr** [comment] 2015-02-02 21:30
Warning voltage is already defined in the GUI and is per 1s value.

**Comment by wildflyer** [comment] 2015-02-03 01:43
why ? because the real hott modules by graupner allow only voltage alarm steps by 1/10 Volts. it would be nice to be able to set a value by 1/100 step. it is not important if it is a 1cell value or an absolute value.

**Comment by johnlenfr** [comment] 2015-02-03 06:29
With the accuracy of the mesurement 0.01v will mean something?

**Comment by CopterFail** [comment] 2015-02-03 06:41
@CopterFail, would be interesting to be tested on your GR12S.
Ok , where can I get the cc3d hex file?

**Comment by Pierre-A** [comment] 2015-02-03 08:53
**@wildflyer**, the voltage battery parameters are all coded as 8 bits integers in Cleanflight, that is ( 255 x 1/10 volts) maximum. This is quite simple, consistent with Graupner's and probably enough for general usage considering the accuracy of measurements. Considering 1/100 steps is out of the scope of the current project and would imply other modifications in the code.

**@CopterFail**, I have to fix last few things before opening a PR, but you can PM me and I'll send you the CC3D hex file.

**Comment by wildflyer** [comment] 2015-02-03 12:41
ok,I have my alarms set to 3.6v and would like to lower it a little bit, but 3.5 is already too low. i would need 3.55volts. but if it is not easily possible, no problem :-)

**Comment by Pierre-A** [comment] 2015-02-05 18:25
last news..

I changed strategy to access the Text_Mode informations : from serial (a bit tedious and not really easy) to radial (more intuitive and faster) around a main page from which you access the desired information windows.  See below.

Up to now, I designed 5 pages. Some of them (*Battery* and *ESC/Motors*) are similar to parts of the Configuration tab of the Configurator. *GPS* and *Features* are not completed.

Variable parameters can all be edited from the Graupner TX, directly applied to the current config and EEPROM saved (or not).
Seven other information pages could be added to this through a second selection_window accessed from the first (switch with next and prev arrows of the TX).

The PR is coming...

![1-selection page](https://cloud.githubusercontent.com/assets/8274225/6066294/6337b58c-ad6c-11e4-8aa6-e18cfd1f5070.jpg)
![2-measures](https://cloud.githubusercontent.com/assets/8274225/6066297/66c640ec-ad6c-11e4-8242-ff3eb1c91ffa.jpg)
![3-battery](https://cloud.githubusercontent.com/assets/8274225/6066303/6b442b16-ad6c-11e4-8fa0-e7c330fa389a.jpg)
![4-esc motors](https://cloud.githubusercontent.com/assets/8274225/6066305/6e527146-ad6c-11e4-9e23-195cb1b11110.jpg)
![5-pid controller](https://cloud.githubusercontent.com/assets/8274225/6066310/7220a482-ad6c-11e4-8fe3-dfe4a9618ea4.jpg)
![6-pid values](https://cloud.githubusercontent.com/assets/8274225/6066312/755d832c-ad6c-11e4-9e0e-844e8393afdc.jpg)

**Comment by johnlenfr** [comment] 2015-02-05 18:41
WOW! Very nice job @Pierre-A !
Would like to test it as soon as possible!

You're insane in coding, now I can't want wait the PR!

**Comment by wildflyer** [comment] 2015-02-05 23:13
looks better and better! and you already have a tab for gps and baro :-) ... is it possible to change pid values directly without having to hit "save" ? so you could tune the values in flight very fast!

**Comment by Pierre-A** [comment] 2015-02-06 10:45
I did not put any condition for accessing the Text mode, so, yes, you can change any parameter while flighing (not tested).. but be safe, you'll have to be very careful to what/where your eyes are looking at..

**Comment by wildflyer** [comment] 2015-02-06 12:44
in the pictures I see the word "save". do I have to scroll down to the word "save" everytime I change a value, or is the value automatically saved when a value is changed ? that would be faster when "inflight" :-)

**Comment by johnlenfr** [comment] 2015-02-06 12:47
The current changed value is changed but not stored in EEPROM until you hit save.
So if you change the value you test it, if it is OK you save it.
If you reboot before saving, the value is not stored so not saved.

**Comment by Pierre-A** [comment] 2015-02-06 12:48
once a value is changed it is immediatly applied to the system. But it is lost when you turn off the board, unless you "save" which writes the value in EEPROM.

**Comment by Pierre-A** [comment] 2015-02-06 12:53
**@wildflyer**, PM me for testing:wink:

**Comment by wildflyer** [comment] 2015-02-06 12:54
oh great :-) that is the best solution! I pm :-)

**Comment by wildflyer** [comment] 2015-02-06 12:57
pierre, I dont know how to pm here, I wrote you a normal email.

**Comment by johnlenfr** [comment] 2015-02-06 13:00
@Pierre-A , if you already have the hex you can send it to me for tests if you want.
If not I will wait for the next release with your PR.

**Comment by wildflyer** [comment] 2015-02-06 14:48
ok, I have connection and I can edit :-) ... if I change values in battery page, the arrow keys are reversed (up=minus etc). I can change a value, and it changes in gui also (after refresh) but when I hit "save" in the tx, it doesnt save and the cursor in the page doesnt move anymore. i have to press "esc" on tx  or reset all. so saving to eeprom doesnt work ...

also, the battery voltage doesnt trigger the alarm, I set the valu to 3.9V and my battery is much below it, but it doesnt alarm. how do I have to setup the alarm ?

it feels great to access the parameters with the tx :-)

**Comment by wildflyer** [comment] 2015-02-06 17:13
I found out, you can save! :-) when you go to the "save" line, you have to move cursor twice, but saving works only in pid value tab. in batterytab I cannot save ...

**Comment by johnlenfr** [comment] 2015-02-06 18:11
Please, be patient, this is the first tests. 
This is not a final version so there are bugs, it is normal.
All we are doing here is report to Pierre these bugs so that he can change the code for better performances.

I have the same issues than you but we have to be patient.

The work is awesome even if there is some bugs now.
The structure is here: menus / pages / selection / saving in EEPROM.

There might be some adjustments but Pierre will make it when he can.
It is not easy stuff so please be gentle.

**Comment by wildflyer** [comment] 2015-02-06 18:22
patient ? the earlier we can report issues, the better, isnt it ? :-)
is your alarm sounding ? mine is "flashing" only on measures tab

so right now, I can edit all parameters and save them in the pid values tab, so I can say, editing is working :-)

**Comment by CopterFail** [comment] 2015-02-07 12:40
@Pierre-A: Still no success to connect the gr12s to the cc3d flex port .. I've updated the gr12s to the latest firmware (using ch5, so I don't think it a hardware problem of the receiver). Now I'm running out of ideas, I'll check the cc3d hardware (flex port), What about the mx12 software - may it have influence?

**Comment by Pierre-A** [comment] 2015-02-07 16:43
*CopterFail*, you should connect your RX (PPM signal) on pin 3 of the RC_input port and telemetry on pins 4 and 5 (Sofserial). Then set parameters with CLI accordingly.

**Comment by wildflyer** [comment] 2015-02-07 16:59
and dont forget to program channel 5 of the receiver to "telemetry" ...

pierre, battery alarm is not making a sound on my tx, only visually you can see the alarm in the measures tab (blinking, but this blinking confuses the cursor display in the tab). is your battery alarm making sounds on your tx ?

**Comment by Pierre-A** [comment] 2015-02-07 17:52
yes I know the blinking confuses the cursor, this should be changed.
The alarm is not a beep but a vocal saying something like "under power" in the earphones (so far I don't know how I can activate the beep ..)

**Comment by wildflyer** [comment] 2015-02-07 17:58
ah ok, I have to know that :-)

but in a video in an above post (johns ?), there it is shown, that it is beeping when under voltage. wasnt that a firmware made by you ?

**Comment by johnlenfr** [comment] 2015-02-07 18:52
Hello @Pierre-A , hello @wildflyer,
I have the same issue. Beeping and voice alarm doesn't work.
Maybe "hottEAMMessage->warning_beeps = 0x??;" is not working in the code.
You can't separate the "beep" and the "voice alarm", they are the same warning. If nothing is connected to the audio output, the radio "beep", if there is something plug in, the radio is "voice alarming".

If the warning beep doesn't work with the EAM module, try the one in the GAM module, and the correct value is:
"hottGAMMessage->warning_beeps = 0x10; // beep"

That's what you heard in my video.

If you use the GAM module you'll have more functions as gauge and percentage of lipo.
But if you use the gauge, you'll have to reconsider the calculateBatteryPercentage() function that is false for now. Lipo voltage VS remaining% is not a linear function.
A thing to modify next time. For now it is not a problem.

Good coding ;)

**Comment by CopterFail** [comment] 2015-02-08 17:41
Ok, I've tried softserial, identical setting (except serial_port_x_scenario) - it works with softserial, but fails with the two physical serial ports. 
I use a 1N4148, as I've always done (taulabs, my own software, etc). But I'll try a resistor too.
Sometimes I'm kicked out of the cleanflight page back to an rx page. But reentering the cleanflight page is no problem.
Good work!

**Comment by CopterFail** [comment] 2015-02-08 18:02
The same result for the resistor (1k). Softserial is the only working configuration on my hardware ( cc3d/gr12s ), but not compatible with the led_strip .

**Comment by ebawho** [comment] 2015-02-11 00:56
Does anyone have Pierres latest hex? this looks like amazing work and would love to test it out.

**Comment by Pierre-A** [comment] 2015-02-11 08:02
**@ebawho**, first hex was buggy, next (coming) will be ok.. mail me plz so you'll get it soon

**Comment by johnlenfr** [comment] 2015-02-11 08:07
Even if it was buggy, it is a pretty damn improvement!

**Comment by ebawho** [comment] 2015-02-11 15:34
@pierre-a, If bug finding is something I can help with, I would gladly. I sent you an email a few days ago to the address listed on your page. 

Thanks again for your time and contributions.

**Comment by Pierre-A** [comment] 2015-02-11 16:25
**@ebawho**, OK Cod (?), you're on my list,
The new hex is coming (should be tomorrow)
thanks all for your patience...

**Comment by CopterFail** [comment] 2015-02-12 18:19
Oh, a new version ;) 
CC3D / GR12s / MX12 / Softserial connect but is not very constant. On connection problems the cleanflight page is left and the last receiver page is shown, indicating than this is the last page, "<" in the top right corner. After 1-3s the sign change to "<>" and the the cleanflight page can be reentered. No editing is lost. 
The MX12 also increases values by pressing the down-key. Editing receiver settings in text-mode, the down-key decreases the value.

**Comment by wildflyer** [comment] 2015-02-12 22:45
ok, I tested the new version. saving now works in every menu :-). pid tuning works as well as in version 1. up/down menu navigation is reversed when sth is displayed in "reverse". but the alarm sound is still not working :-( ... what could be the problem ? maybe to try johns GAM instead of EAM, because this is alarming ?

**Comment by Pierre-A** [comment] 2015-02-13 08:20
**@wildflyer**, strange as it works fine for me (Naze32 + GR16 + MX20). What is your configuration ?
If you change the warning voltage (*Battery* screen), you'll hear a beep a soon as  the (ncells x warning volt.) value comes higher than the current Vbatt (it is real time). You can change the *Alarm period* on the *Measures* screen (fast beep if set to 0).
Remember that Text mode has nothing to do with HoTT modules.
**@CopterFail**, don't completely understand what happens with your GR12S. What do you mean "the Cleanflight page is left" ? does everything work after this 1-3s first step ?

**Comment by CopterFail** [comment] 2015-02-13 08:55
If you watch one of the cleanflight page or do some editing, the cleanflight page disappears and you see the receiver page (different time some seconds to some minutes). After some seconds you can enter the cf page again and continue. It looks like a timing problem, cf miss to respond ...
Has anyone this working with cc3d and a hardware serial port?

**Comment by johnlenfr** [comment] 2015-02-13 09:16
@all : 

Everything works fine with my setup: Naze32 Softserial2 +GR16 (including alarm, and warnings).
Buttons stays inverted but it doens't matter. You test in one direction, if not correct you invert and it is OK.

Will do some tests with my quads with GR12L when this PR will be merged, I hope soon?

@CopterFail : maybe you have to touch a button always, or the radio is going back to previous screen automaticaly? And so this is not a bug but a security?

**Comment by Pierre-A** [comment] 2015-02-13 10:53
I added a *Current meter* page with parameters as seen on the *Configuration* tab of the GUI. Plus the Current_meter type selection (ADC or virtual). On the example below,  *virtual* is selected, so the drawn current and battery capacity are real time updated on the *Measures* page.
![current_meter page](https://cloud.githubusercontent.com/assets/8274225/6186182/986674ea-b376-11e4-92a0-5301308e2d5a.jpg)

**Comment by CopterFail** [comment] 2015-02-13 13:26
@johnlenfr: no, this also happens during editing. I think there is still a timing problem, not specific to the text mode (?). Hott is sensible if the response is too fast or the gap between the bytes is too small.

**Comment by wildflyer** [comment] 2015-02-13 18:12
pierre, I flew today and tried a lot, but alarm is still not working :-( ... I have mx-12, gr-12sh+ and naze32 full. what could I test to find out whats wrong ?

**Comment by Pierre-A** [comment] 2015-02-13 19:53
**@wildflyer**, the alarm period is not (yet ?) a CLI parameter, so it comes back to 10s (default value) each time you reboot. Plz, would you precise a bit more on how you try to make it work. You should hear a beep with a period as set in the *Measures* page (and very fast if set to 0s). That said, I don't know wether the MX12 and MX20 are different on the alarm management or not.

**Comment by wildflyer** [comment] 2015-02-14 00:19
ok, I set the alarm voltage to 3.8V. when the voltage becomes lower, the voltage display in "measures" gets inverted, but no sound. all other hott modules I have (voltage, gps and vario) are working with alarm, no problem. everything should be set up correctly ... it must be sth in your code that maybe is set up correctly for the mx-20, but not for my mx-12. I also tried a mx-16, but there the same ... all firmwares of every hardware is the newest ... what could I maybe try to find out whats wrong ?

**Comment by ernieift** [comment] 2015-02-14 09:02
Have a Look in the TauLabs code. There are alarm codes to sent. These codes generate beeps or spoken messages for each alarm.

**Comment by Pierre-A** [comment] 2015-02-14 10:17
Yes for sure,
I used the alarm code (0x10) which is given for the main voltage alarm (as described in hott.h file). **Ernieift** do you have a Taulabs link to compare with ?
I (re)verified on my MX20 (with GR16 RX) and it works fine when  Vbatt is below  (ncells x warning volt.) or/and when RSSI level is below 50% (low warning level set in the code for the moment). This gives a beep (with the period set in the *Measures* page) or the "under voltage" voice alarm in the earphones when connected.
**Wildflyer**, supposing that all Graupner TX's respond to the same error codes, I don't know what would be different with MX12 or MX16. Maybe a dumb question.. but can you check the volume signals in the base settings of your MX ?

Btw, I tested on CC3D and everything works as expected.

**Comment by ernieift** [comment] 2015-02-14 11:18
Here is the link to my version:
https://github.com/TauLabs/TauLabs/blob/next/flight/Modules/UAVOHoTTBridge/inc/uavohottbridge.h

**Comment by Pierre-A** [comment] 2015-02-14 11:47
Thanks for it !
your description is a bit more complete but with identical  informations.
Just a comment, the description of the TX buttons (lines 128-133) should be updated : it's 0x0B to 0x07 respectively instead of 0xEB to 0xE7, these last values combining EAM_ID (4 MSB) and button_ID (4 LSB).
Did you code some Text mode ?

**Comment by wildflyer** [comment] 2015-02-14 12:10
the volume is at "4". all normal system sounds are working ok. the voltage warning of the receiver is alarming immediatly when I set more than 5V. it must be sth within your code ... the hott modules are alarming very well, they are "text mode" too ? ... I think, there is maybe missing some (pre)initialization of the sound, that is neccessary in "my case" and not necessary in "others cases" ... the inverted voltage display in "measures" shows, that the alarm is "triggered", but the sound itself is NOT. when the headphones are plugged in, I can hear the voltage read by the voice, but the voice does NOT say "under voltage" or sth. ...

**Comment by ernieift** [comment] 2015-02-14 12:14
I wasn't able to get a request from the MX-12. The code should return a blank page then. You can use Vario to send 21 bytes of text.

**Comment by johnlenfr** [comment] 2015-02-14 12:16
@wildflyer : are you using both modules from Graupner and telemetry from Cleanflight Naze on the telemetry port of your Tx?

**Comment by wildflyer** [comment] 2015-02-14 12:19
john, not at the same time  I only have the cleanflight connected. I had voltage module connected before, that was alarming ... but the receiver itself is a module too that is capable of alarming for testing, and it is working (alarming) as it should ...

**Comment by johnlenfr** [comment] 2015-02-14 12:22
You should reboot your radio if you're changing telemetry modules "on the fly"

Is this with your GR12s that the problem comes?

Could you try with another setup for exemple a GR12 or GR16 or GR24 ?
Just to be sure it is not something else?

**Comment by johnlenfr** [comment] 2015-02-14 12:26
@Pierre-A : the generateWarning() function is interesting in https://github.com/TauLabs/TauLabs/blob/next/flight/Modules/UAVOHoTTBridge/uavohottbridge.c

;)

**Comment by wildflyer** [comment] 2015-02-14 12:31
in this copter everything is soldered and glued in, at the moment I cannot change receivers easily ... it is the gr-12sh+ receiver.

**Comment by johnlenfr** [comment] 2015-02-14 12:35
Ok, I think you'll have to test with another receiver to be sure that your problem doen't come with your GR12SH+ receiver.
When done, debug will advance ;)

**Comment by ebawho** [comment] 2015-02-14 16:21
So far pretty much everything has been working well for me so far. I get
the beep tone from my mx20 as the low voltage warning, but I typically use
a small speaker so I can have the voltage read to me. When I do this, and
the voltage alarm is activated, I get Frau Graupner yelling "reciever
strength" over and over again at times so quickly that she is unable to get
through the whole word reciever. Not sure if this is a code problem or an
mx20 problem.

When I have the voice set to a momentary switch to read the voltage, she
says "sensor one voltage, x.x volts"

**Comment by wildflyer** [comment] 2015-02-14 16:41
it cant be the receiver, because the command to trigger the alarm is displayed in the "measures" tab ... so the command is received by the transmitter ...

**Comment by Pierre-A** [comment] 2015-02-14 16:51
**Ebawho**, Frau Graupner is gone be out of voice soon...  what is the alarm period on page *Measures* ?
When you hear the reading voltage message, aren't you in binary mode ?

image of the day : I added a *Receiver* page  (info you find on the "Receiver" tab of the Configurator.
![receiver](https://cloud.githubusercontent.com/assets/8274225/6200305/1398e840-b472-11e4-81f7-776fbc3dd32f.jpg)

**Comment by ebawho** [comment] 2015-02-14 17:07
So when I am in the measures page, the period is set to 10 seconds and the voice says "under voltage" as it should every 10 seconds. If I return to the normal telemetry page it repeats "receiver" like crazy, and I am unable to use my momentary switch to hear my voltage. 

Otherwise everything works great. It really is amazing to have all these options. Wish my expensive mikrokopter setup had the same level of integration! 

Cody

**Comment by wildflyer** [comment] 2015-02-14 18:29
ernie, do you have a mx-12 too ? is the alarm working ?

**Comment by ernieift** [comment] 2015-02-14 21:31
I have MX-12,MX-16,GR-16 and some GR12SH+. All tested with Taulabs and working. Audio is tested via Blueetooth Headset and AndroidApp. No issues so far. I may be wrong but timing is critical in HoTT. Normally it doesn't care if it beeps or speak.

**Comment by wildflyer** [comment] 2015-02-15 02:45
ernie, can you maybe help to find out why the alarm is not alarming in my case ?

**Comment by ernieift** [comment] 2015-02-15 21:01
I would check the usual suspects. Check all firmwares of RX and TX. Sorry but i haven't a naze for testing.

**Comment by wildflyer** [comment] 2015-02-16 00:31
I checked everything ... it must be sth in the software ... everything else works well :-) ... but without voltage alarm :-(

**Comment by CopterFail** [comment] 2015-02-18 16:06
@ernieift : Oh, I thought the GR12SH+ did not support telemetry (except a single voltage input). So I should try this too....

**Comment by ernieift** [comment] 2015-02-18 16:32
@CopterFail after updating to SUMD the GR-12SH+ support telemetry on channel 5 too. ;)

**Comment by wildflyer** [comment] 2015-02-18 16:40
copter fail: yes telemetry works with all modules :-) ... pls try the the gr12sh+ and cleanflight telemetry and let us know!

**Comment by wildflyer** [comment] 2015-02-22 01:11
okay, it does not seem, that the alarm will be sounding in the near future, so I went back to the setup I had before: hott voltage module and editing with mobile phone and usb :-(.
the hott voltage module works very well with gr12sh+ and mx-12, so the problem is somewhere in pierres code!

pierre, the hott voltage module has a text mode too, you can set battery levels and alarm, and it is sounding and displaying undervoltage as expected. the sound is ONLY alarming when NOT in text mode(editing), maybe that a hint what is the software problem ? also the voltage module is displayed as "general" not as "electric", maybe there is a bug in the EAM, and that is responsible for not working with any hott setup ?

so now I have waited many weeks for the this cleanflight hott telemetry, just to go back where I had been before :-(
editing pids works with some bugs in the interface, but without the voltage alarm sounding that all is useless ...

**Comment by Pierre-A** [comment] 2015-02-22 05:40
**@wildflyer**, I don't know what can be wrong in your case as I do not make any assumption about the TX.
Remember that *text* and *binary* modes are completely different and separated. In the *.hex* I provided, I introduced an alarm on the battery voltage in the binary EAM response. Can you check that ? You just select EAM and put a high value for the warning cell voltage (under CLI or text mode) so that the alarm can be activated. And look at what happens in the EAM **binary** page. You should get the same response as ebawho's a few days ago (each 10s or what you set in text mode and fast beep in binary).

**Comment by wildflyer** [comment] 2015-02-22 14:48
when I adjust the cell voltage in text mode and go to binary mode, the voltage gets inverted, but no alarm can be heard. so the right undervoltage is detected by the software and triggered, just the execution of the sound is not working. this must be some kind of bug in your code or in the eam. because the original graupner voltage module works very well (text mode and binary!) with exactly the same setup and settings so it must be sth within your code. maybe the sound needs some more "initialisation" before you call the trigger or sth like that ?

**Comment by wildflyer** [comment] 2015-02-22 14:50
with this module I am using everything is working well: 
http://www.graupner.de/de/products/a60b6f0a-69bf-4cc7-a98a-38e6d1624498/33630/product.aspx

**Comment by Pierre-A** [comment] 2015-02-23 16:01
**@wildflyer**, I know this voltage module as I have 3 of them I don't use anymore :smirk:
So I dug out one and tried it for telemetry instead of telemetry coming from the Naze (GR16 and MX20). This gives the same "under voltage" vocal message which makes me think both telemetry configurations use the same alarm message code (0x10).
To go one step further, I compiled a specific  *Cleanflight_Naze.hex*  to scan the possible messages registered in the TX by choosing any alarm code (up to 100) on the *Measures* page (which revealed 64 different messages on my MX20). Then, once an alarm message is selected, it is used for both binary and text modes.
Would you like to test that on your MX12 ?

**Comment by wildflyer** [comment] 2015-02-23 17:35
ok, I will re-solder the naze to the receiver to test, it would be great if I would not need the voltage module anymore too :-). pls send the hex file to my email.

**Comment by wildflyer** [comment] 2015-02-23 21:01
ok, it works now! :-)
thx pierre for the new version. also I checked the new features, version display works, also the features are displayed as I programmed them. the only confusing thing is the "reverse cursor" when editing sth, but that is ok .... great, now the important battery warning is working and editing all data with tx is really  great! :-)

**Comment by blucable** [comment] 2015-04-29 02:36
Hey guys I own a GR-24L and I currently have a Hott GPS/Vario connected to it, and my Rx is connected on my Naze32 using the SUMD signal with one cable and I cannot get cleanflight to see my GPS module. I read all the comments above mine but I still don't get what configuration I need to choose in cleanflight to make this work. Any help is greatly appreciated, thanks!

**Comment by Pierre-A** [comment] 2015-05-01 14:55
**@blucable** : I understand your GPS/vario is connected to the T pin of the GR24L. So it is part of the Hott chain and should be recognized  by your Hott TX (and displayed on the appropriate page). The SUMD line only carries channels command and no Hott informations ; that's why Cleanflight cannot see your GPS module.
You have to keep in mind that Cleanflight only emulates the output of EAM and GPS modules using internal data provided by external sensors. Reading the Hott information (other than the clock) has not been coded.
If you want to get GPS informations in Cleanflight, you need a basic GPS module with Rx/Tx connected to a free port of the Naze (with the appropriate CLI parameters setting). For your config, I am not sure this Hott GPS/Vario outputs any other signal than the Hott one.

**Comment by blucable** [comment] 2015-05-05 13:14
@Pierre-A thank you so much for the information, that explains it well. I will be getting a separate module.

**Comment by Pierre-A** [comment] 2015-05-05 13:17
you're welcome !

**Comment by johnlenfr** [comment] 2015-10-12 07:14
Hi all,

I have an issue with the last firmwares 1.9.0 and 1.10.0 with telemetry.
When the quad is beeping, the radio don't and I have weird values on the radio: for 3S I have sometime 0v and sometimes 23v wich is not very good.

Can we do something about that?

It's disturbing because when the quad is away, we can't hear the beeper on the quad, so the radio beeper was good. But it doesn't work properly since FW 1.9.0.

Thanks

**Comment by Pierre-A** [comment] 2015-10-16 14:01
Hey John, sorry for the delay , was abroad these times..
I was not aware (or forgot) that the battery code has been modified a while ago (see PR #952, ....) and did not notice that issue.
So I did a few tests and you're right, something has been broken but I don't know where yet. 
The Vbat value is now filtered and it's variation is not instantaneous in the GUI (very slow up and down response). Moreover, the hott binary mode is not processed as it should (no more adressed in case of a low batt event).
Have to dig in that.

**Comment by jcowgar** [comment] 2015-10-16 14:22
What is the status of this FR and being able to edit parameters right from my Graupner radio? Is there a branch somewhere with this code? It'd be a bummer to loose it, seems like it's getting a bit old now :-(

**Comment by Pierre-A** [comment] 2015-10-16 14:31
**@jcowgar** see this PR #792
I should rebase it short term (scheduled for november)

**Comment by johnlenfr** [comment] 2015-10-16 17:15
Hi Pierre, thanks for the reply.
Will wait until the problem is solved, maybe in 1.11?
Many thanks for the work,
Cheers,
John

**Closed** 2017-02-25 16:58 UTC
Labels: enhancement
