### ISSUE TITLE
Serial passthrough for minmosd

### ISSUE THREAD

**Issue by Jahnkeanater** [cleanflight/cleanflight#1587] opened 2015-12-16 04:43 UTC
Not an issue but idk where to post ideas for features.
There is already gps pass through and 1wire so why not add a command to pass through the serial data to connect to a minmosd through the FC. This would make customizing the osd easier and remove the need for any programmer to set things up.

**Comment by krzysztofmatula** [comment] 2015-12-16 07:59
Not sure about the minimosd gui, but for programming the DTR line is also necessary as far as I know...

**Comment by JacobGrigg** [comment] 2015-12-16 09:17
I believe the DTR line is only required for firmware updates and not configured changes. Alternatively if the minimosd has a reset button it can be used instead of the DTR line.

**Comment by flounderscore** [comment] 2015-12-16 11:01
+1

Even to just change settings that can't be accessed using the odd menu. If DTR is required for reset, power cycling should do the trick as well.

**Comment by dkisselev** [comment] 2015-12-16 21:15
This is a duplicate of another issue, and I believe someone got the changeover 90% implemented, just never opened a PR.

**Comment by huston007** [comment] 2015-12-17 21:39
Anyway please please let's make this done. I'm going to bury my minim osd inside frame and I don't want to disassembly the frame every time I want to configure it

**Comment by LaserLock** [comment] 2015-12-18 09:29
:+1:

**Comment by Arakon** [comment] 2015-12-20 09:51
Actually, DTR may be skippable if the MWOSD author would implement a reset code that could be sent over MSP, similar to how configurator can send a reset code to cleanflight to get into flash mode.
I'm sure he'd do it.

**Comment by btimby** [comment] 2016-01-15 18:54
I published a release including this feature for testing:

https://github.com/btimby/cleanflight/releases/tag/v.11.0-SerialPassthrough

**Comment by Arakon** [comment] 2016-01-15 22:49
Works for me to configure a micro minimosd on a CC3D nano.
- CP2102 via Mainport
- OSD on Flexport
- serialpassthrough 2 115200 rxtx
Disconnecting, then connecting to the com port of the CP2102 via the MWOSD gui works.

Flashing via Arduino does not, but I believe that is because it's attempting to access the bootloader via 57600 baud:
Using Programmer              : arduino
         Overriding Baud Rate          : 57600
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xb9
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x0b
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xad
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xb9
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x0b
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xad
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xb9
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x0b
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xad
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xb9

avrdude done.  Thank you.

I didn't actually try with 57600 baud to see if that will allow programming, though.

**Comment by btimby** [comment] 2016-01-16 02:19
I have not been able to get flashing to work yet. There are two main issues:

1. You have to reset the OSD before an upload can proceed. This is usually done by AVRDude using DTR, which is not connected to the FCB.
2. The timing is critical as the bootloader waits only a short time to receive the upload.

I will be working on something, but I don't have an easy way of flashing yet, so this is config-only for now.

**Comment by btimby** [comment] 2016-01-16 02:21
This issue is a duplicate of #1439

**Comment by DerDominik** [comment] 2016-02-09 19:28
Tested it today with a SPRacingF3 and a MicroMinimOSD ("serialpassthrough 2") and seems to work without any failures after closing cleanflight GUI and starting MWOSD-GUI.
Great Work!! Hope it will be integrated in betaflight or cleanflight next time

**Closed** 2016-10-31 18:12 UTC

**Comment by hydra** [comment] 2016-11-01 09:40
done.
