### ISSUE TITLE
MultiWii 2.3+ PID controller with Cleanflight

### ISSUE THREAD

**Issue by MJ666** [cleanflight/cleanflight#321] opened 2015-01-06 23:37 UTC
We are actually testing the MultiWii 2.3 PID controller implementation with CF and small nanocopters. Actual CF is still using the MultiWii 2.2 PID algorithm as the default beside 2 two other PID algorithms. The goal was mainly to improve yaw handling. The code is already flight tested and is available for more field testing from here:

https://github.com/MJ666/cleanflight/tree/MultiWii_PID_32

The MultiWii 2.3 PID controller will be activated with set pid_controller = 3. Please be prepared to the need to retune the PID values of your copter.

Please don't use with a Tricopter since the code is not fully implemented for this special case.

If there is more interest to get this integrated in CF I can make an related pull request. I also can provide binaries for testing on the different targets if needed. Please let me know.

**Comment by MJ666** [comment] 2015-01-07 07:57
Binaries for testing are available here: www.mj-home.de/CF/cleanflight_MW_PID_23.zip

**Comment by MJ666** [comment] 2015-01-08 00:09
For the Nanocopters the MultiWii 2.3 PID controller is creating strange oscillations. We was not able to tune them but we have not tested the code on larger copters yet. For this reason we implemented an hybrid MultiWii PID controller. Roll and pitch is using the MultiWii 2.2 algorithm and yaw is using the 2.3 algorithm. With this controller the flight tests looking very promising.The hybrid PID controller can be activated with set pid_controller = 4. The code is alredy commited in the fork mentioned above and I will update the firmware binarys next days for more easy testing.

**Comment by MJ666** [comment] 2015-01-08 22:15
Binaries for testing the MultiWii 2.3 and MultiWii hybrid PID controller are available here: www.mj-home.de/CF/cleanflight_PID_23_Hybrid.zip

set pid_controller = 3 (MultiWii 2.3 PID's)
set pid_controller = 4 (MultiWii Hybrid PID's)

**Comment by ledvinap** [comment] 2015-01-08 22:53
After quick scan of diffs, maybe gyroData[axis] is scaled differently in CF and MW. This could possibly cause stability problems ...

**Comment by MJ666** [comment] 2015-01-09 01:23
@ledvinap 
Very good catch. I have really overseen this. With fix of the scaling the MultiWii 2.3 PID controller is performing well now. I have updated the binaries.

**Comment by hydra** [comment] 2015-01-09 01:48
excellent, i will try and have a look at this soon, been busy with the configurator the last few days.

**Comment by wildflyer** [comment] 2015-01-09 18:01
the best pid controler, that I have flown so far! ... much better than baseflight or cleanflight :-)

**Comment by MJ666** [comment] 2015-01-09 19:21
Cool, which one you tried. MultiWii 2.3, the hybrid or both versions? I guess you mean the MultiWii 2.3 version.

**Comment by wildflyer** [comment] 2015-01-09 19:27
oh sorry for misunderstanding, I could not find the time to test your version yet. but I fly a lot of multiwii 2.3 copters and they feel much better, especially flying acro moves than baseflight/cleanflight. moving to cleanflight was a bit of a step back in "flying performance"(at least for me), but a big step forward in features, cant wait for the pid2.3 in cleanflight to test :-)

**Comment by MJ666** [comment] 2015-01-09 20:05
Feel free to test them. I build binary's for this and you can download from here..

**Comment by fiveangle** [comment] 2015-01-09 20:44
MJ666: so you will fix CF Scaler then put build with MW 2.3 PID controller here for us to test ?

**Comment by MJ666** [comment] 2015-01-09 21:17
Yes the binaries are already updated with the gyro scaling as stated in my comment above Hydra's.
In the meantime we find out the scaling was fixing the oscillation issues we have seen on our Nanocopters for the MultiWii 2.3 PID controller. But unfortunately the yaw was getting worse again for us. We are now test a build with no scaling on yaw for both additional PID controllers.

**Comment by hydra** [comment] 2015-01-11 23:56
I wanna try this but just so busy!

**Comment by MJ666** [comment] 2015-01-17 19:21
Unfortunately not much feedback here. With our Nanocopters we are quit successfully with the pid_controller 3 (MiltiWii 3.2) and removed gyro scaling on yaw. If there is no more interest I will go ahead with removing the hybrid PID controller and make this part of the AlienWii targets only. We like to use this pid controller as default for the two AlienWii targets. I will wait a few more days and than make the related pull request.

**Comment by wildflyer** [comment] 2015-01-17 19:34
hi,

it is not that there is no interest! in january with snowing outside its not priority to fly quads for many pilots ... please include the 2.3 pid controller into cleanflight! :-)

**Comment by MJ666** [comment] 2015-01-18 14:52
Rebased the code to actual Cleanflight release. Binaries are not updated.

**Comment by andymac4182** [comment] 2015-01-20 08:56
I would love to give this a go. I should have a quad back and flying shortly.

**Comment by hydra** [comment] 2015-01-20 17:38
Thanks for doing the rebase MJ666.  This is probably something I can try while i'm out here in France.

**Comment by MJ666** [comment] 2015-01-21 00:51
Did another rebase. Likely I should go ahead and remove the hybrid controller since its not realy needed after the MultiWii 2.3 is working. One idea is to make the yaw gyro scale configurable? The default will be divided by 4 (this is how the code is now) and it can be switched of which give for now best results for the Nanocopters and can be default for the AlienWii controllers. Feedback her will be appreciated.  
No new binaries are build.

**Comment by MJ666** [comment] 2015-01-21 22:07
Make yaw gyro scale dependent on AlienWii targets. Blackbox related updates fro the additional PID controllers.

**Comment by andymac4182** [comment] 2015-01-23 06:17
I have started tuning my Quad for this PID controller and so far it seems okay. Hopefully I will get some time for some testing this weekend.

**Comment by MJ666** [comment] 2015-01-23 07:53
This really sounds good. I'm very interested how this PID controller works for others. Actually I'm also looking to try the PID controller form Harakiri which is working quite well on the STM32 platform and is using partially floating point calculation.

**Comment by fiveangle** [comment] 2015-01-25 23:06
I can't seem to get my Openlog to capture a thing after loading your binaries.  Is this was a known limitation ?  If not, I'll continue to root cause the issue.

-=dave

**Comment by MJ666** [comment] 2015-01-25 23:18
Rebasd the code today again. Binarys are not updated since a while. I can build  new binaries if you rely on the very latest version. The blackbox support was added sometimes on the way. Please see the commit history of my branch.

**Comment by fiveangle** [comment] 2015-01-26 06:30
Your answer was ambiguous :)

Is Blackbox support for PID controller #3 included in the binaries you linked to above, or not ?

Thx for the work in this.

-=dave

**Comment by MJ666** [comment] 2015-01-26 07:22
Her are the new binaries build from latest code today: http://www.mj-home.de/CF/cleanflight_PID23_260115.zip

**Comment by hydra** [comment] 2015-01-26 11:59
@MJ666 Is this ready to merge now?

**Comment by MJ666** [comment] 2015-01-26 12:25
@hydra 
We can merge. The code is working and we using PID Controller 3 (MultiWii 2.3) quite successfully for the AlienWii22 and Nanocopters. This will give us for now the best performance. Not sure if we should remove the Hybrid PID version (PID Controller 4) to avoid issues later on? I'm actually also working on porting the PID code from Harakiri which is using more floating point math calculations Many people in the past have seen quite some improvements in PID performance here in comparison to BF/CF and I want to give it a try. Please let me know your thoughts.

**Comment by hydra** [comment] 2015-01-26 14:01
I'm certainly up for trying out different pid controllers, especially ones that use floating point math with commonly accepted/standard units.  The existing ones are quite self-contained so are easy to compile in/out as needed should we decide to adopt/drop ones in the future.

I'll take a look at merging this tonight.

**Comment by hydra** [comment] 2015-01-26 14:02
@MJ666 Is there a PR for this already?

**Comment by MJ666** [comment] 2015-01-26 14:42
Yust created the PR. :-)

**Comment by MJ666** [comment] 2015-01-26 17:12
Here are the new binaries build from latest code today: 

http://www.mj-home.de/CF/cleanflight_PID23_260115.zip

Includes Blackbox support (bug fixed) and fixed Autotune

**Comment by hydra** [comment] 2015-01-26 17:18
This is now merged, closing.  Please create new issues and PR's if problems are found.

**Closed by hydra** 2015-01-26 17:18 UTC
Labels: critical, enhancement

**Comment by fiveangle** [comment] 2015-02-17 07:27
@MJ666 - what's the best method/forum to chat with you about your 2.3 implementation in the latest RC 1.7.2 ? I finally got a chance to try it out and essentially could not lower P enough to get a 220 class quad with Oneshot125 on 4S to stop shaking at hover. Went down to even "1" and it just resulted in an unflyable mess. 3S on the same quad was similar, but would at least not violently shake constantly below P of 17.

When I get back in front of the computer, I'll try to see of the Blackbox recordings worked (and if they are of any use).

-=dave

**Comment by MJ666** [comment] 2015-02-17 08:03
Please send me an PM in any of the forums I'm active. We can communicate via Skype. Lets see if I can help here. We actually have good success with the Nanocopters and PID 3 and 5. I was not flying larger copters with the new PID's yet.

**Comment by thenickdude** [comment] 2015-02-17 10:55
fiveangle: I'm happy to provide an extra set of eyes on those Blackbox logs. It could be that the I or D parameters are actually causing the issue which is visible in the Blackbox PID graphs.

**Comment by fiveangle** [comment] 2015-02-21 19:52
Logs from two short flights one on 3S, the other on 4S.  PID controller 3, pitch and yaw P-1.0, I-0.20, all others default (files named with D-0.01 are incorrect, it was default D-0.23 as screenshot below).  It's very much difficult to fly, yet oscillations at 4S are very pronounced.  If I bump P above 17, 3S oscillates too.   I've tried down as far as P-0.1 (which resulted in crash) with same oscillations at 4S.  Default PID (4.0/0.35/0.23) completely unflyable at 4S, and pretty much everything in between.

Could the non-pitch/roll PID defaults be causing this issue ?

http://5angle.com/tmp/cleanflight/BBL-fiveangle-2015feb21.7z

![2015-02-21_1148](https://cloud.githubusercontent.com/assets/2219447/6315707/cb81c1e6-b9bf-11e4-8818-6c05482a8339.png)

-=dave

**Comment by fiveangle** [comment] 2015-02-21 19:54
Looking at the recorded data, does the Pitch P look stuck between 35-40 ?  Could it not be honoring the CFC Pitch P adjustment ?

-=dave

**Comment by MJ666** [comment] 2015-02-21 21:09
Are your motors running vibration free?
Do you have checked the balance of your propellers?
What kind of frame do you use size, carbon (very stiff) or something else? 
How do you have mounted your FC.

Likely we should continue the discussion in the CF thread. This will also cause more users can provide feedback.

**Comment by thenickdude** [comment] 2015-02-21 22:31
@fiveangle: typically "I" builds up to its limit and just stays precisely there until the correction needs to change direction. It's usually just sitting as a nearly-straight line.

The largest contributor to the oscillation by far is your D term:

![Oscillations](http://i.imgur.com/PFBu4nG.png)

Check out the roll graph, the blue line is the gyro measuring the oscillation and the dashed yellow line is the D correction, it's massive. The other terms oscillate but not nearly as much. Reduce roll D.

**Comment by fiveangle** [comment] 2015-02-22 01:44
@thenickdude - thanks so much for the tip.  I see that there's a need for a Blackbox analysis primer that details the expected quantitative values and how to generally interpret them (this one a prime example).

Dropping D to 0.10 completely removed the gross oscillation.  Not once using BF or CF on the 2.2 or "rewrite" had the D ever made any appreciable difference while flying on this 220 B.O. quad (fast-fly in rate mode only).

As I begin to better understand these logs, I'll see if I might be able to draft up a newbie primer.

Thanks again for the help !

-=dave
