### ISSUE TITLE
Feature Request:adding Light Telemetry (LTM) as telemetry output option for low bandwidth telemetry links (e.g. FSK audio modem)

### ISSUE THREAD

**Issue by idefixsin** [cleanflight/cleanflight#327] opened 2015-01-08 02:31 UTC
Feature request to include native LTM (Light Telemetry) support in Cleanflight.
LTM fits low baudrates like 1200/2400 bauds so this can be used to send data
to the Groundstation (e.g. Antenna Tracker) over long range transmission like OpenLRSng transparent 
serial link, or FSK modem trough fpv Video TX Audio channel.

Following is a link to a LTM converter project (Ghettoproxy by KipK) running on a Arduino mini board and supporting the following input protocols:

    MAVLink
    UAVTalk
    Multiwii MSP
    GPS NMEA (ascii)
    GPS UBlox (binary)

Ghettoproxy: https://github.com/KipK/Ghettostation/tree/master/GhettoProxy

Given the support of Multiwii MSP in the converter I assume that native implementation (not knowing about current space and processing restrictions on popular HW such as Naze32 of course) could be straight forward?

Thanks for exploring !

**Comment by thenickdude** [comment] 2015-01-14 11:36
This is the code that actually sends the LTM packets:

https://github.com/KipK/Ghettostation/blob/0530118e1f11556e226d6166544d8f51a423b295/GhettoProxy/LightTelemetry.cpp

What hardware supports receiving LTM, is there anything standard?

**Comment by idefixsin** [comment] 2015-01-15 09:59
Hi Nick,

I'm not sure whether it is a standard or not but I see that LTM was implemented in Taulabs and Openpilot. KipK's Antenna Tracker (Arduino based) uses it for low baudrate telemetry links (OpenLRSng or, what I'm doing at the moment with APM, FSK Audio Modem).

**Comment by hydra** [comment] 2015-01-15 10:25
This is a duplicate of #36 - please search before creating new issues.  Closing.  Discussions should occur on the other issue.  Labels can be used to mark issues as feature requests.

**Closed by hydra** 2015-01-15 10:25 UTC
