### ISSUE TITLE
LED Strobe

### ISSUE THREAD

**Issue by alvins82** [cleanflight/cleanflight#645] opened 2015-03-19 06:50 UTC
It would be great if a strobe effect was possible using LEDs driven by Naze32. Similiar to how these work - http://www.hobbyking.com/hobbyking/store/__26238__LED_PCB_Strobe_White_3_3_5_5V.html.

Ideally you could program the strips with this behaviour. Ultimately can program stuff like this in - http://en.wikipedia.org/wiki/Navigation_light#Aviation_navigation_lights.

**Comment by handsomejackuk** [comment] 2015-03-21 11:27
just regular leds would be good to and not just ws2812b...

**Comment by hydra** [comment] 2015-03-21 12:48
Duplicate of #471. See also #473

**Closed by hydra** 2015-03-21 12:48 UTC
Labels: enhancement
