### ISSUE TITLE
GPS Tab issue

### ISSUE THREAD

**Issue by waslater** [cleanflight/cleanflight#435] opened 2015-01-27 18:35 UTC
I currently have a Crius ublox neo-6m (no integrated compass) connected to my naze board. This one: (http://www.massiverc.com/PrestaShop/en/409-neo-6-v31-gps-neo-6m-module.html) It appears to work, but I can never get GPS hold mode to enable. Wjhen everything is powered on outside, the GPS tab shows a fix and an accurate latitude and longitude (I don't know how), but nothing appears in the satellite strength indicator box. I know the GPS hold mode is not engaging because the 5 satellites are not present. 

Does anyone know how or why cleanflight is detecting the presence of my gps, giving me a lat/lon, but not idicating individial signal strengths from any of the satellites?

**Comment by hydra** [comment] 2015-01-27 18:41
Yes, it's probably because the SVINFO packet is not being received by the FC.  Please either use the auto configuration cli option or configure your gps unit manually as per the documentation.

The issue is not in the configurator.  There is no issue retreiving the gps signal strength from the fc, just that the fc has not receivd signal strength information.

closing the issue, please re-open if you are are sure your configuration is correct after verifying it.

**Closed by hydra** 2015-01-27 18:41 UTC

**Comment by waslater** [comment] 2015-01-27 18:47
Thanks for the tips, I'll try the auto configuration again.

On Tuesday, January 27, 2015, Dominic Clifton <notifications@github.com>
wrote:

> Closed #435 <https://github.com/cleanflight/cleanflight/issues/435>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight/issues/435#event-225561052>.
>


-- 
William A. Slater

*Mobile: (843) 813-4053*
*Office: (910) 432-0717*
*waslater@gmail.com* <waslater@gmail.com>
*william.a.slater18.mil@mail.mil <william.a.slater18.mil@mail.mil>*
