### ISSUE TITLE
ESC passthrough for flashing?

### ISSUE THREAD

**Issue by dkisselev** [cleanflight/cleanflight#687] opened 2015-03-30 08:19 UTC
Just curious if anyone's considered implementing an ESC passthrough mode,

For those ESC's that have servo connector flashable firmware it'd be awesome if CF could act as a linker so you can change blheli settings, update firmware, etc.

Biggest roadblocks I could see are: 

a) Handing off the serial port might be an issue (the configurator would need to send a "passthrough to motor 1" command, and disconnect, then when the FC is powercycled it would go back to configurator mode).

b) Flash space, not sure how much we have right now but it might be wasteful for a feature that's not directly related to flight.

Coolest benefit is that it saves you from having to take your quad apart to get at those connectors when trying to tweak things.

**Comment by ledvinap** [comment] 2015-03-30 08:30
Is there some programming protocol documentation?

**Comment by dkisselev** [comment] 2015-03-30 08:36
Nothing explicit that I know of, but it's been implemented as an Arduino sketch: https://github.com/c---/ArduinoUSBLinker/blob/master/ArduinoUSBLinker.ino

That's what I used to flash my Afro ESC's and it worked great. Basically takes serial input and bitbangs the right sequence out.

**Comment by hydra** [comment] 2015-03-30 10:10
Duplicate of #216

**Closed** 2015-03-30 10:10 UTC
Labels: duplicate, enhancement
