### ISSUE TITLE
Feature Request - Split softserial

### ISSUE THREAD

**Issue by geigerg** [cleanflight/cleanflight#289] opened 2015-01-02 10:02 UTC
Is there a way to split softserial code. This would be great if there is a way to use softserial 2 and ledstrip or softserial 1 and current-sensing.

**Comment by johnlenfr** [comment] 2015-01-02 10:44
Would like to use SUMD+LED_STRIP+TELEMETRY on softserial too.

**Comment by hydra** [comment] 2015-01-02 18:54
there are other related improvements coming to softserial but it's complicated due to timer channel allocation.

please search for existing issues/requsts before posting since this is a duplicate of #113

**Closed by hydra** 2015-01-02 18:54 UTC

**Comment by geigerg** [comment] 2015-01-04 09:47
I'm not that sure about #113 is covering using LED_Strip and softserial at the same time.
