### ISSUE TITLE
SP Racing lockup when enabling telemetry

### ISSUE THREAD

**Issue by watak** [cleanflight/cleanflight#1354] opened 2015-09-28 10:29 UTC
I have a genuine SP Racing with Betaflight cleanflight 1.10 RC2.
Running RX_SERIAL - SBUS  on UART3 and MSP Telemetry on UART1 if I enable Telemtry in Configuration the board freezes up every time I try and arm.

I see the same issue was found in an earlier version:

https://github.com/cleanflight/cleanflight/issues/50

Thanks.

**Comment by SteveAmor** [comment] 2015-09-28 10:37
Is this a duplicate of #1346 ?

**Comment by watak** [comment] 2015-09-28 10:56
Not sure it's exactly the same, telemetry still works when "telemetry" feature is disabled in the configuration.

here is my Ports config.

![screen shot 2015-09-28 at 12 51 23](https://cloud.githubusercontent.com/assets/2764901/10133700/ae3c7992-65df-11e5-9a11-0f4e42d4d16d.png)

If the board is armed then the motors briefly spinup and then it locks up (solid red and blue light). Nothing to do but cycle power.

**Comment by watak** [comment] 2015-09-28 11:02
Well disabling telemetry on UART1 but enabling it as a config solved the issue, sorry about the duplicate in this case.

**Comment by hydra** [comment] 2015-10-02 10:55
duplicate of #1346 - search before raising new issues please.

**Closed by hydra** 2015-10-02 10:55 UTC
